<?php

namespace Database\Seeders;

use App\Models\Laundry;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LaundrySeeder extends Seeder
{
    public function run(): void
    {
        $laundries = [
            // 1. Smart Laundry Unnes
            [
                'name' => 'Smart Laundry Unnes',
                'location' => 'Jl. Kalimasada No.1a, Sekaran',
                'whatsapp' => '+62 877-4611-1127',
                'maps_link' => null,
                'open_hours' => 'Buka 24 Jam',
                'open_on_holidays' => true,
                'capacity_status' => 'Normal',
                'price_regular_kg' => 6000,
                'duration_regular_days' => 2,
                'has_express' => true,
                'price_express_kg' => 12000,
                'duration_express_hours' => 4,
                'price_suit_almet' => 15000,
                'duration_suit_almet_hours' => 6,
                'price_white_shirt' => 8000,
                'price_shoes' => 25000,
                'price_iron_only' => 4500,
                'accept_kebaya_dress' => false,
                'has_delivery' => true,
                'min_delivery_kg' => 3,
                'accept_qris' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 2. MY WASH LAUNDRY SELF SERVICE
            [
                'name' => 'MY WASH LAUNDRY SELF SERVICE',
                'location' => 'Jl. Taman Siswa No.4, Sekaran',
                'whatsapp' => '+62 878-8407-7947',
                'maps_link' => null,
                'open_hours' => '06.00 - 00.00',
                'open_on_holidays' => true,
                'capacity_status' => 'Ramai',
                'price_regular_kg' => 5000,
                'duration_regular_days' => 1,
                'has_express' => true,
                'price_express_kg' => 15000,
                'duration_express_hours' => 2,
                'price_suit_almet' => 12000,
                'duration_suit_almet_hours' => 4,
                'price_white_shirt' => 7000,
                'price_shoes' => null,
                'price_iron_only' => 4000,
                'accept_kebaya_dress' => false,
                'has_delivery' => false,
                'min_delivery_kg' => null,
                'accept_qris' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 3. Nyuci Laundry Self Service UNNES
            [
                'name' => 'Nyuci Laundry Self Service UNNES',
                'location' => 'Jl. Taman Siswa No.35, Sekaran',
                'whatsapp' => '+62 882-0074-39287',
                'maps_link' => null,
                'open_hours' => '07.00 - 00.00',
                'open_on_holidays' => true,
                'capacity_status' => 'Sangat Ramai',
                'price_regular_kg' => 5000,
                'duration_regular_days' => 1,
                'has_express' => true,
                'price_express_kg' => 15000,
                'duration_express_hours' => 2,
                'price_suit_almet' => 15000,
                'duration_suit_almet_hours' => 3,
                'price_white_shirt' => 8000,
                'price_shoes' => 25000,
                'price_iron_only' => null,
                'accept_kebaya_dress' => false,
                'has_delivery' => false,
                'min_delivery_kg' => null,
                'accept_qris' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 4. NN Laundry UNNES
            [
                'name' => 'NN Laundry UNNES',
                'location' => 'Jl. Taman Siswa (Dekat Lapangan Banaran)',
                'whatsapp' => '+62 858-6408-0489',
                'maps_link' => null,
                'open_hours' => '08.00 - 21.00',
                'open_on_holidays' => true,
                'capacity_status' => 'Normal',
                'price_regular_kg' => 5500,
                'duration_regular_days' => 2,
                'has_express' => true,
                'price_express_kg' => 10000,
                'duration_express_hours' => 6,
                'price_suit_almet' => 13000,
                'duration_suit_almet_hours' => 12,
                'price_white_shirt' => 6500,
                'price_shoes' => 20000,
                'price_iron_only' => 4500,
                'accept_kebaya_dress' => true,
                'has_delivery' => true,
                'min_delivery_kg' => 3,
                'accept_qris' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 5. Laundry Papa Jalan Taman Siswa
            [
                'name' => 'Laundry Papa Jalan Taman Siswa',
                'location' => 'Jl. Taman Siswa No.8b',
                'whatsapp' => '+62 896-7101-5466',
                'maps_link' => null,
                'open_hours' => '08.00 - 23.00',
                'open_on_holidays' => true,
                'capacity_status' => 'Normal',
                'price_regular_kg' => 5000,
                'duration_regular_days' => 2,
                'has_express' => true,
                'price_express_kg' => 11000,
                'duration_express_hours' => 5,
                'price_suit_almet' => 14000,
                'duration_suit_almet_hours' => 10,
                'price_white_shirt' => 7000,
                'price_shoes' => 22000,
                'price_iron_only' => 4500,
                'accept_kebaya_dress' => false,
                'has_delivery' => true,
                'min_delivery_kg' => 5,
                'accept_qris' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 6. Laundry Room UNNES
            [
                'name' => 'Laundry Room UNNES',
                'location' => 'Jl. Pete Raya No.04',
                'whatsapp' => '+62 857-4135-2710',
                'maps_link' => null,
                'open_hours' => '08.00 - 21.00',
                'open_on_holidays' => false,
                'capacity_status' => 'Normal',
                'price_regular_kg' => 5000,
                'duration_regular_days' => 2,
                'has_express' => true,
                'price_express_kg' => 10000,
                'duration_express_hours' => 5,
                'price_suit_almet' => 13000,
                'duration_suit_almet_hours' => 12,
                'price_white_shirt' => 7000,
                'price_shoes' => null,
                'price_iron_only' => 4000,
                'accept_kebaya_dress' => false,
                'has_delivery' => true,
                'min_delivery_kg' => 3,
                'accept_qris' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 7. Laundry Express dan Antar Jemput - Laju Unnes Patemon
            [
                'name' => 'Laju Unnes Patemon',
                'location' => 'Jl. Patemon No.39',
                'whatsapp' => '+62 858-2000-8775',
                'maps_link' => null,
                'open_hours' => '08.00 - 21.00',
                'open_on_holidays' => true,
                'capacity_status' => 'Normal',
                'price_regular_kg' => 5500,
                'duration_regular_days' => 2,
                'has_express' => true,
                'price_express_kg' => 11000,
                'duration_express_hours' => 6,
                'price_suit_almet' => 14000,
                'duration_suit_almet_hours' => 8,
                'price_white_shirt' => 7500,
                'price_shoes' => 22000,
                'price_iron_only' => 4500,
                'accept_kebaya_dress' => true,
                'has_delivery' => true,
                'min_delivery_kg' => 4,
                'accept_qris' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 8. Laundry Express 1 Jam Siap Patemon
            [
                'name' => 'Laundry Express 1 Jam Siap Patemon',
                'location' => 'Jl. Mr. Koesbiyono Tjondrowibowo',
                'whatsapp' => '+62 821-4637-2089',
                'maps_link' => null,
                'open_hours' => '07.00 - 00.00',
                'open_on_holidays' => true,
                'capacity_status' => 'Sangat Ramai',
                'price_regular_kg' => 6000,
                'duration_regular_days' => 2,
                'has_express' => true,
                'price_express_kg' => 15000,
                'duration_express_hours' => 1,
                'price_suit_almet' => 15000,
                'duration_suit_almet_hours' => 3,
                'price_white_shirt' => 8000,
                'price_shoes' => 25000,
                'price_iron_only' => null,
                'accept_kebaya_dress' => false,
                'has_delivery' => false,
                'min_delivery_kg' => null,
                'accept_qris' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 9. Wangi Laundry UNNES
            [
                'name' => 'Wangi Laundry UNNES',
                'location' => 'Gg. Cemp. Sari No.33C, Sekaran',
                'whatsapp' => '+62 857-1334-7323',
                'maps_link' => null,
                'open_hours' => '08.00 - 21.00',
                'open_on_holidays' => true,
                'capacity_status' => 'Normal',
                'price_regular_kg' => 5000,
                'duration_regular_days' => 3,
                'has_express' => true,
                'price_express_kg' => 10000,
                'duration_express_hours' => 8,
                'price_suit_almet' => 12000,
                'duration_suit_almet_hours' => 24,
                'price_white_shirt' => 6000,
                'price_shoes' => 15000,
                'price_iron_only' => 4000,
                'accept_kebaya_dress' => false,
                'has_delivery' => true,
                'min_delivery_kg' => 5,
                'accept_qris' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 10. Albarokah Laundry 2 (UNNES)
            [
                'name' => 'Albarokah Laundry 2 (UNNES)',
                'location' => 'Gg. Cemp. Sari, Sekaran',
                'whatsapp' => '+62 858-1988-8955',
                'maps_link' => null,
                'open_hours' => 'Buka 24 Jam',
                'open_on_holidays' => true,
                'capacity_status' => 'Ramai',
                'price_regular_kg' => 4500,
                'duration_regular_days' => 3,
                'has_express' => true,
                'price_express_kg' => 9000,
                'duration_express_hours' => 12,
                'price_suit_almet' => 10000,
                'duration_suit_almet_hours' => 24,
                'price_white_shirt' => 5000,
                'price_shoes' => null,
                'price_iron_only' => 3500,
                'accept_kebaya_dress' => false,
                'has_delivery' => true,
                'min_delivery_kg' => 5,
                'accept_qris' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 11. Laundry "O"
            [
                'name' => 'Laundry "O"',
                'location' => 'Gg. Cemp. Sari No.41',
                'whatsapp' => '+62 813-9026-2458',
                'maps_link' => null,
                'open_hours' => '07.00 - 23.00',
                'open_on_holidays' => true,
                'capacity_status' => 'Normal',
                'price_regular_kg' => 5500,
                'duration_regular_days' => 2,
                'has_express' => true,
                'price_express_kg' => 10000,
                'duration_express_hours' => 5,
                'price_suit_almet' => 13000,
                'duration_suit_almet_hours' => 12,
                'price_white_shirt' => 7500,
                'price_shoes' => 20000,
                'price_iron_only' => 4500,
                'accept_kebaya_dress' => false,
                'has_delivery' => true,
                'min_delivery_kg' => 5,
                'accept_qris' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 12. JK LAUNDRY
            [
                'name' => 'JK LAUNDRY',
                'location' => 'Jl. Cempaka Sari No.22c',
                'whatsapp' => '+62 822-4207-9974',
                'maps_link' => null,
                'open_hours' => '08.00 - 20.00',
                'open_on_holidays' => true,
                'capacity_status' => 'Normal',
                'price_regular_kg' => 5000,
                'duration_regular_days' => 2,
                'has_express' => false,
                'price_express_kg' => null,
                'duration_express_hours' => null,
                'price_suit_almet' => 12000,
                'duration_suit_almet_hours' => 24,
                'price_white_shirt' => 6000,
                'price_shoes' => 18000,
                'price_iron_only' => 4000,
                'accept_kebaya_dress' => false,
                'has_delivery' => true,
                'min_delivery_kg' => 4,
                'accept_qris' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 13. Best Laundry Self Service
            [
                'name' => 'Best Laundry Self Service',
                'location' => 'Jl. Taman Siswa, Sekaran',
                'whatsapp' => '+62 857-8627-4780',
                'maps_link' => null,
                'open_hours' => '07.00 - 00.00',
                'open_on_holidays' => true,
                'capacity_status' => 'Normal',
                'price_regular_kg' => 6000,
                'duration_regular_days' => 1,
                'has_express' => true,
                'price_express_kg' => 14000,
                'duration_express_hours' => 3,
                'price_suit_almet' => 16000,
                'duration_suit_almet_hours' => 6,
                'price_white_shirt' => 9000,
                'price_shoes' => 30000,
                'price_iron_only' => 5000,
                'accept_kebaya_dress' => true,
                'has_delivery' => true,
                'min_delivery_kg' => 4,
                'accept_qris' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 14. MR KLIN Laundry Unnes
            [
                'name' => 'MR KLIN Laundry Unnes',
                'location' => 'Jl. Raya Banaran, Sekaran',
                'whatsapp' => '+62 812-2762-3377',
                'maps_link' => null,
                'open_hours' => '07.00 - 21.00',
                'open_on_holidays' => true,
                'capacity_status' => 'Normal',
                'price_regular_kg' => 5500,
                'duration_regular_days' => 2,
                'has_express' => true,
                'price_express_kg' => 11000,
                'duration_express_hours' => 6,
                'price_suit_almet' => 14000,
                'duration_suit_almet_hours' => 12,
                'price_white_shirt' => 7000,
                'price_shoes' => 20000,
                'price_iron_only' => 4500,
                'accept_kebaya_dress' => true,
                'has_delivery' => true,
                'min_delivery_kg' => 3,
                'accept_qris' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 15. LAJU Laundry Antar Jemput
            [
                'name' => 'LAJU Laundry Antar Jemput',
                'location' => 'Jl. Marga Satwa Jl. Raya Banaran',
                'whatsapp' => '+62 857-9999-2053',
                'maps_link' => null,
                'open_hours' => '09.00 - 21.00',
                'open_on_holidays' => false,
                'capacity_status' => 'Normal',
                'price_regular_kg' => 5000,
                'duration_regular_days' => 2,
                'has_express' => true,
                'price_express_kg' => 10000,
                'duration_express_hours' => 8,
                'price_suit_almet' => 13000,
                'duration_suit_almet_hours' => 24,
                'price_white_shirt' => 6000,
                'price_shoes' => 15000,
                'price_iron_only' => 4000,
                'accept_kebaya_dress' => false,
                'has_delivery' => true,
                'min_delivery_kg' => 0,
                'accept_qris' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 16. Amanah Laundry
            [
                'name' => 'Amanah Laundry',
                'location' => 'Jl. Raya Sekaran',
                'whatsapp' => '+62 882-3329-0981',
                'maps_link' => null,
                'open_hours' => '05.30 - 23.00',
                'open_on_holidays' => true,
                'capacity_status' => 'Normal',
                'price_regular_kg' => 5500,
                'duration_regular_days' => 2,
                'has_express' => true,
                'price_express_kg' => 10000,
                'duration_express_hours' => 6,
                'price_suit_almet' => 13000,
                'duration_suit_almet_hours' => 12,
                'price_white_shirt' => 6000,
                'price_shoes' => 20000,
                'price_iron_only' => 4500,
                'accept_kebaya_dress' => true,
                'has_delivery' => true,
                'min_delivery_kg' => 5,
                'accept_qris' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ];
        // Bikin variabel counter khusus buat ngelacak nomor gambar
    $imageIndex = 1;

    foreach ($laundries as $laundry) {
        // Logika cerdas: Kalau counter nyentuh angka 2, kita paksa dia loncat ke 3
        if ($imageIndex === 2) {
            $imageIndex++; 
        }

        // Tembak URL gambarnya ke array
        // (Pastiin ekstensinya bener ya, antara .png atau .jpeg sesuai file Word-nya)
        $laundry['image_url'] = "/images/vendors/image{$imageIndex}.webp"; 

        Laundry::create($laundry);

        // Tambah 1 ke counter untuk putaran selanjutnya
        $imageIndex++;
    }
    }
    
}
