<?php

namespace Database\Seeders;

use App\Models\Mua;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MuaSeeder extends Seeder
{
    public function run(): void
    {
        $muas = [
            // 1. Prameshwari MUA
            [
                'name' => 'Prameshwari MUA',
                'social_link' => '@prameshwari.mua',
                'location' => 'Perum Ayodya Sekaran Cluster Belalang No.48',
                'whatsapp' => '+62 812-2697-8900',
                'specialty' => 'Flawless, Soft Glam',
                'include_hair_hijab' => true,
                'rent_accessories' => true,
                'home_service' => true,
                'accept_qris' => true,
                'duration_hours' => 1.5,
                'daily_capacity' => 4,
                'price_sidang' => 150000,
                'price_wisuda' => 250000,
                'price_party' => 200000,
                'home_service_fee' => 15000,
                'price_hairdo' => 45000,
                'price_hijabdo' => 30000,
                'price_softlens_nails' => 40000,
                'price_accessories_rent' => 25000,
                'price_companion' => 120000,
                'booking_rules' => 'Maksimal H-3',
                'dp_terms' => 'Rp 50.000',
                'created_at' => now(),
                'updated_at' => now()
            ],
            // 2. MUA SEMARANG UNNES Lookby Maheswarini
            [
                'name' => 'MUA SEMARANG UNNES Lookby Maheswarini',
                'social_link' => '@lookbymaheswarini',
                'location' => 'Jl. Taman Siswa No.65, Sekaran',
                'whatsapp' => '+62 857-0281-5868',
                'specialty' => 'Tradisional, Bold',
                'include_hair_hijab' => true,
                'rent_accessories' => true,
                'home_service' => true,
                'accept_qris' => true,
                'duration_hours' => 2.0,
                'daily_capacity' => 3,
                'price_sidang' => 175000,
                'price_wisuda' => 300000,
                'price_party' => 250000,
                'home_service_fee' => 20000,
                'price_hairdo' => 50000,
                'price_hijabdo' => 35000,
                'price_softlens_nails' => 45000,
                'price_accessories_rent' => 50000,
                'price_companion' => 150000,
                'booking_rules' => 'H-7',
                'dp_terms' => '30%',
                'created_at' => now(),
                'updated_at' => now()
            ],
            // 3. Elisabeth MUA + Hairdo Semarang
            [
                'name' => 'Elisabeth MUA + Hairdo Semarang',
                'social_link' => '@elisabethmua.id',
                'location' => 'Kampoeng Symphony, Blok B35, Pudakpayung',
                'whatsapp' => '+62 857-1394-4289',
                'specialty' => 'Korean Look, Dewy',
                'include_hair_hijab' => true,
                'rent_accessories' => true,
                'home_service' => true,
                'accept_qris' => true,
                'duration_hours' => 2.0,
                'daily_capacity' => 3,
                'price_sidang' => 200000,
                'price_wisuda' => 350000,
                'price_party' => 250000,
                'home_service_fee' => 30000,
                'price_hairdo' => 60000,
                'price_hijabdo' => 35000,
                'price_softlens_nails' => 50000,
                'price_accessories_rent' => 35000,
                'price_companion' => 150000,
                'booking_rules' => 'H-7',
                'dp_terms' => '50%',
                'created_at' => now(),
                'updated_at' => now()
            ],
            // 4. Ayune Salon
            [
                'name' => 'Ayune Salon',
                'social_link' => '@ayunesalon.unnes',
                'location' => 'Jl. Raya Banaran, RT.3/RW.4, Sekaran',
                'whatsapp' => '+62 887-0662-0631',
                'specialty' => 'Natural Flawless',
                'include_hair_hijab' => false,
                'rent_accessories' => false,
                'home_service' => true,
                'accept_qris' => true,
                'duration_hours' => 1.0,
                'daily_capacity' => 5,
                'price_sidang' => 120000,
                'price_wisuda' => 200000,
                'price_party' => 150000,
                'home_service_fee' => 0,
                'price_hairdo' => 35000,
                'price_hijabdo' => 25000,
                'price_softlens_nails' => 30000,
                'price_accessories_rent' => 0,
                'price_companion' => 100000,
                'booking_rules' => 'H-2',
                'dp_terms' => 'Rp 50.000',
                'created_at' => now(),
                'updated_at' => now()
            ],
            // 5. Bybun_makeup
            [
                'name' => 'Bybun_makeup',
                'social_link' => '@bybun_makeup',
                'location' => 'Gg. Dhipo 1, Kalisegoro',
                'whatsapp' => '+62 858-7647-9659',
                'specialty' => 'Barbie Look, Bold Eyes',
                'include_hair_hijab' => true,
                'rent_accessories' => true,
                'home_service' => true,
                'accept_qris' => true,
                'duration_hours' => 1.5,
                'daily_capacity' => 4,
                'price_sidang' => 160000,
                'price_wisuda' => 260000,
                'price_party' => 200000,
                'home_service_fee' => 15000,
                'price_hairdo' => 45000,
                'price_hijabdo' => 30000,
                'price_softlens_nails' => 40000,
                'price_accessories_rent' => 25000,
                'price_companion' => 130000,
                'booking_rules' => 'H-3',
                'dp_terms' => '30%',
                'created_at' => now(),
                'updated_at' => now()
            ],
            // 6. IZZA beauty Salon
            [
                'name' => 'IZZA beauty Salon',
                'social_link' => '@izzabeautysalon',
                'location' => 'Gg. Cemp. Sari No.24b, Sekaran',
                'whatsapp' => '+62 857-2274-9903',
                'specialty' => 'Clean Look, Soft Glam',
                'include_hair_hijab' => false,
                'rent_accessories' => false,
                'home_service' => true,
                'accept_qris' => true,
                'duration_hours' => 1.5,
                'daily_capacity' => 5,
                'price_sidang' => 130000,
                'price_wisuda' => 220000,
                'price_party' => 170000,
                'home_service_fee' => 10000,
                'price_hairdo' => 35000,
                'price_hijabdo' => 20000,
                'price_softlens_nails' => 35000,
                'price_accessories_rent' => 0,
                'price_companion' => 100000,
                'booking_rules' => 'H-2',
                'dp_terms' => 'Bebas',
                'created_at' => now(),
                'updated_at' => now()
            ],
            // 7. Salon Semarang | Salon UNNES | Lydia Beauty Salon
            [
                'name' => 'Lydia Beauty Salon UNNES',
                'social_link' => '@lydiabeautysalon',
                'location' => 'Gedung KWU UNNES, Lantai 2, Sekaran',
                'whatsapp' => '+62 895-3840-07077',
                'specialty' => 'Natural, Cepat & Praktis',
                'include_hair_hijab' => true,
                'rent_accessories' => true,
                'home_service' => false,
                'accept_qris' => true,
                'duration_hours' => 1.0,
                'daily_capacity' => 8,
                'price_sidang' => 150000,
                'price_wisuda' => 250000,
                'price_party' => 180000,
                'home_service_fee' => 0,
                'price_hairdo' => 40000,
                'price_hijabdo' => 25000,
                'price_softlens_nails' => 35000,
                'price_accessories_rent' => 20000,
                'price_companion' => 120000,
                'booking_rules' => 'H-1 Bisa',
                'dp_terms' => 'Tidak Wajib',
                'created_at' => now(),
                'updated_at' => now()
            ],
            // 8. Mua Gunungpati, ibu yuli rias
            [
                'name' => 'Ibu Yuli Rias Gunungpati',
                'social_link' => '@yulirias.gunungpati',
                'location' => 'Sumurrejo, Kec. Gn. Pati',
                'whatsapp' => '+62 858-6695-9795',
                'specialty' => 'Tradisional, Manglingi',
                'include_hair_hijab' => true,
                'rent_accessories' => true,
                'home_service' => true,
                'accept_qris' => true,
                'duration_hours' => 2.0,
                'daily_capacity' => 3,
                'price_sidang' => 180000,
                'price_wisuda' => 300000,
                'price_party' => 250000,
                'home_service_fee' => 25000,
                'price_hairdo' => 50000,
                'price_hijabdo' => 30000,
                'price_softlens_nails' => 45000,
                'price_accessories_rent' => 50000,
                'price_companion' => 150000,
                'booking_rules' => 'H-7',
                'dp_terms' => '50%',
                'created_at' => now(),
                'updated_at' => now()
            ],
            // 9. Hadi & Co Sanggar Rias Pengantin
            [
                'name' => 'Hadi & Co Sanggar Rias',
                'social_link' => '@hadiandco_smg',
                'location' => 'Jl. Muntal, Ngijo, Kec. Gn. Pati',
                'whatsapp' => '+62 857-4036-3701',
                'specialty' => 'Premium Glam, Flawless',
                'include_hair_hijab' => true,
                'rent_accessories' => true,
                'home_service' => true,
                'accept_qris' => true,
                'duration_hours' => 2.5,
                'daily_capacity' => 2,
                'price_sidang' => 250000,
                'price_wisuda' => 450000,
                'price_party' => 350000,
                'home_service_fee' => 40000,
                'price_hairdo' => 75000,
                'price_hijabdo' => 50000,
                'price_softlens_nails' => 60000,
                'price_accessories_rent' => 100000,
                'price_companion' => 200000,
                'booking_rules' => 'H-14',
                'dp_terms' => '50%',
                'created_at' => now(),
                'updated_at' => now()
            ],
            // 10. rfglamo
            [
                'name' => 'rfglamo',
                'social_link' => '@rfglamo',
                'location' => 'Gg. Cemp. Sari, Sekaran',
                'whatsapp' => '+62 822-8972-4444',
                'specialty' => 'Peachy Look, Natural',
                'include_hair_hijab' => false,
                'rent_accessories' => false,
                'home_service' => true,
                'accept_qris' => true,
                'duration_hours' => 1.0,
                'daily_capacity' => 6,
                'price_sidang' => 110000,
                'price_wisuda' => 180000,
                'price_party' => 150000,
                'home_service_fee' => 0,
                'price_hairdo' => 30000,
                'price_hijabdo' => 20000,
                'price_softlens_nails' => 30000,
                'price_accessories_rent' => 0,
                'price_companion' => 90000,
                'booking_rules' => 'H-2',
                'dp_terms' => 'Bebas',
                'created_at' => now(),
                'updated_at' => now()
            ],
            // 11. SabellaAmalia Makeup
            [
                'name' => 'SabellaAmalia Makeup',
                'social_link' => '@makeupbysabella_',
                'location' => 'Padangsari',
                'whatsapp' => '+62 813-2775-2802',
                'specialty' => 'Matte, Tahan Lama',
                'include_hair_hijab' => true,
                'rent_accessories' => true,
                'home_service' => true,
                'accept_qris' => true,
                'duration_hours' => 2.0,
                'daily_capacity' => 3,
                'price_sidang' => 220000,
                'price_wisuda' => 350000,
                'price_party' => 280000,
                'home_service_fee' => 35000,
                'price_hairdo' => 50000,
                'price_hijabdo' => 35000,
                'price_softlens_nails' => 50000,
                'price_accessories_rent' => 40000,
                'price_companion' => 150000,
                'booking_rules' => 'H-7',
                'dp_terms' => '40%',
                'created_at' => now(),
                'updated_at' => now()
            ],
            // 12. Maudy Makeup Artist
            [
                'name' => 'Maudy Makeup Artist',
                'social_link' => '@maudy.makeup',
                'location' => 'Semarang',
                'whatsapp' => '+62 838-3889-8870',
                'specialty' => 'Soft Glam',
                'include_hair_hijab' => true,
                'rent_accessories' => true,
                'home_service' => true,
                'accept_qris' => true,
                'duration_hours' => 2.0,
                'daily_capacity' => 3,
                'price_sidang' => 200000,
                'price_wisuda' => 350000,
                'price_party' => 250000,
                'home_service_fee' => 40000,
                'price_hairdo' => 55000,
                'price_hijabdo' => 40000,
                'price_softlens_nails' => 45000,
                'price_accessories_rent' => 50000,
                'price_companion' => 160000,
                'booking_rules' => 'H-7',
                'dp_terms' => '50%',
                'created_at' => now(),
                'updated_at' => now()
            ],
            // 13. Tikaness Makeup Artist
            [
                'name' => 'Tikaness Makeup Artist',
                'social_link' => '@tikaness.mua',
                'location' => 'Semarang Barat',
                'whatsapp' => '+62 812-1829-0757',
                'specialty' => 'Flawless, Natural',
                'include_hair_hijab' => true,
                'rent_accessories' => false,
                'home_service' => true,
                'accept_qris' => true,
                'duration_hours' => 1.5,
                'daily_capacity' => 4,
                'price_sidang' => 180000,
                'price_wisuda' => 280000,
                'price_party' => 220000,
                'home_service_fee' => 30000,
                'price_hairdo' => 40000,
                'price_hijabdo' => 30000,
                'price_softlens_nails' => 40000,
                'price_accessories_rent' => 0,
                'price_companion' => 140000,
                'booking_rules' => 'H-5',
                'dp_terms' => 'Rp 100.000',
                'created_at' => now(),
                'updated_at' => now()
            ],
            // 14. MUA Wong Jowo Kebaya Butik & Rias Pengantin
            [
                'name' => 'MUA Wong Jowo Kebaya',
                'social_link' => '@wongjowokebaya',
                'location' => 'Lamper Tengah',
                'whatsapp' => '+62 858-6576-6668',
                'specialty' => 'Tradisional Jawa, Bold',
                'include_hair_hijab' => true,
                'rent_accessories' => true,
                'home_service' => true,
                'accept_qris' => true,
                'duration_hours' => 2.5,
                'daily_capacity' => 2,
                'price_sidang' => 250000,
                'price_wisuda' => 400000,
                'price_party' => 300000,
                'home_service_fee' => 40000,
                'price_hairdo' => 60000,
                'price_hijabdo' => 40000,
                'price_softlens_nails' => 50000,
                'price_accessories_rent' => 100000,
                'price_companion' => 200000,
                'booking_rules' => 'H-14',
                'dp_terms' => '50%',
                'created_at' => now(),
                'updated_at' => now()
            ],
            // 15. Deeva Karina Make-Up Artist
            [
                'name' => 'Deeva Karina Make-Up Artist',
                'social_link' => '@deevakarina.mua',
                'location' => 'Area Semarang',
                'whatsapp' => '+62 819-0178-1571',
                'specialty' => 'Glamour, Premium',
                'include_hair_hijab' => true,
                'rent_accessories' => true,
                'home_service' => true,
                'accept_qris' => true,
                'duration_hours' => 2.0,
                'daily_capacity' => 2,
                'price_sidang' => 250000,
                'price_wisuda' => 400000,
                'price_party' => 300000,
                'home_service_fee' => 45000,
                'price_hairdo' => 60000,
                'price_hijabdo' => 45000,
                'price_softlens_nails' => 50000,
                'price_accessories_rent' => 75000,
                'price_companion' => 180000,
                'booking_rules' => 'H-14',
                'dp_terms' => '50%',
                'created_at' => now(),
                'updated_at' => now()
            ]
        ];

        $imageIndex = 18;

        foreach ($muas as $mua) {
            // Tembak URL gambarnya, otomatis mulai dari image18.png
            $mua['image_url'] = "/images/vendors/image{$imageIndex}.webp";

            Mua::create($mua);

            // Lanjut ke angka 19, 20, 21, dst.
            $imageIndex++;
        }
    }
}
