<!-- 6-8: Meminta AI Membuat Skenario Percakapan Konseling Karir untuk Anak yang Bingung/Demotivasi -->
<div class="mb-20">
    <img src="https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&q=80&w=1200" alt="Konseling karir" class="w-full h-[400px] md:h-[500px] object-cover rounded-3xl shadow-xl mb-8">
    <h2 class="text-3xl md:text-4xl font-extrabold text-slate-800 mb-6"><i class="fas fa-comments mr-3 text-pink-500"></i>6-8. Meminta AI Membuat Skenario Percakapan Konseling Karir untuk Anak yang Bingung/Demotivasi</h2>
    <div class="prose prose-lg prose-slate max-w-none text-slate-600 leading-relaxed">
        <p>Menghadapi siswa yang benar-benar bingung, apatis, atau bahkan demotivasi terhadap masa depannya adalah salah satu tantangan terberat seorang guru BK. Pertanyaan standar seperti "Apa cita-citamu?" atau "Kamu suka pelajaran apa?" seringkali hanya dibalas dengan angkat bahu atau jawaban "Tidak tahu, Bu." Dalam situasi ini, konselor tidak bisa hanya mengandalkan intuisi; mereka membutuhkan peta pembicaraan yang terstruktur namun fleksibel. AI dapat kita gunakan untuk memproduksi modul skenario percakapan konseling yang kaya akan pertanyaan eksploratif, analogi, dan sudut pandang baru yang mungkin tidak terpikirkan oleh kita. Ini bukan untuk menggantikan ketulusan dan empati kita, melainkan untuk mempersenjatai kita dengan bank pertanyaan yang telah dikurasi oleh AI berdasarkan pola pikir psikologi karir dan coaching, sehingga percakapan bisa bergerak maju dan menemukan titik terang.</p>
        <p>Prompt yang kita berikan harus sangat mendetail tentang persona siswa yang akan kita hadapi. "Buatkan skenario percakapan konseling karir dengan seorang siswa kelas 12 yang sangat pasif. Ia mengatakan tidak punya minat khusus, semua pelajaran terasa 'biasa saja', dan ia memilih jurusan hanya karena ikut-ikutan teman. Di balik sikapnya, ada indikasi ia takut mengambil keputusan salah dan tidak percaya diri dengan kemampuannya. Saya ingin Anda bertindak sebagai konselor karir yang menggunakan pendekatan narrative therapy dan strength-based. Buat dialog dua arah, dimulai dari pertanyaan pembuka yang tidak mengintimidasi. Gunakan metafora atau analogi yang relatable untuk remaja." AI kemudian akan menghasilkan dialog seperti: "Konselor: 'Hei, Andi. Sebelum kita ngomongin jurusan, coba ceritakan, di antara semua game, film, atau akun Youtube yang kamu ikuti, konten apa yang menurutmu bisa bikin kamu lupa waktu? Bukan karena tugas, tapi murni karena penasaran atau seru.'" Ini adalah pintu masuk yang brilian karena menghubungkan dengan dunia yang ia sukai, bukan dengan tuntutan akademik yang membuatnya tertekan.</p>
        <p>Setelah AI memberikan skenario mentah, kita bisa terus menyempurnakannya untuk berbagai cabang respons yang mungkin muncul. "Oke, jika siswa menjawab 'Saya cuma suka nonton video review motor', berikan saya 5 pertanyaan lanjutan yang bisa mengupas nilai-nilai karir dari hobi tersebut. Pertanyaan yang secara tidak langsung mengarah pada minat terhadap aspek engineering, estetika, ekonomi, atau jurnalisme otomotif." AI akan merespons dengan pertanyaan seperti: "Apa yang biasanya pertama kali kamu perhatiin dari review motor? Suara mesinnya, desainnya, atau harganya? Kalau bisa punya motor sendiri, motor yang udah jadi atau yang dioprek sendiri?" Dari sini, arah minat mulai terlihat. Skenario ini menjadi semacam "simulator konseling" yang bisa kita pelajari dan adaptasi sesuai gaya dan kepribadian kita. Kita bisa meminta AI untuk menyisipkan kalimat-kalimat afirmasi atau teknik reframing di momen-momen kunci, misalnya saat siswa menunjukkan sikap pesimis. "Siswa: 'Ah, tapi kan yang bisa masuk teknik itu harus jago matematika, nilai saya jelek.' Konselor (dari AI): 'Saya paham kenapa kamu berpikir begitu. Tapi coba kita lihat dari sisi lain. Mekanik terbaik yang saya tahu jago banget memperbaiki motor tanpa selalu menghitung rumus. Mereka punya insting mekanikal. Mungkin yang kita perlu cari adalah bagaimana kamu bisa mengasah insting itu di dunia kuliah yang tidak terlalu banyak berhitung, seperti desain produk atau teknologi otomotif." Dengan bank skenario ini, kita tidak akan kehabisan kata di hadapan siswa yang diam. Kita memiliki peta untuk menavigasi kabut kebingungan mereka.</p>
    </div>
</div>