
<!-- 6-3: Prompting Prediksi Rasionalisasi SNBP Berdasarkan Tren Nasional dan Keketatan Jurusan -->
<div class="mb-20">
    <img src="https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&q=80&w=1200" alt="Prediksi SNBP" class="w-full h-[400px] md:h-[500px] object-cover rounded-3xl shadow-xl mb-8">
    <h2 class="text-3xl md:text-4xl font-extrabold text-slate-800 mb-6"><i class="fas fa-chart-simple mr-3 text-red-500"></i>6-3. Prompting Prediksi Rasionalisasi SNBP Berdasarkan Tren Nasional dan Keketatan Jurusan</h2>
    <div class="prose prose-lg prose-slate max-w-none text-slate-600 leading-relaxed">
        <p>Mendampingi siswa memilih jurusan di Seleksi Nasional Berdasarkan Prestasi (SNBP) adalah salah satu tugas yang paling mendebarkan dan penuh tanggung jawab. Di satu sisi, kita ingin mendorong siswa untuk mengejar passion-nya, namun di sisi lain kita harus membekali mereka dengan perhitungan rasional yang dingin agar kesempatan mereka tidak terbuang sia-sia. Di sinilah AI dapat berperan sebagai advisor yang mampu melakukan kalkulasi probabilitas dan memberikan perspektif nasional yang seringkali luput dari pandangan kita. Melalui teknik prompting yang tepat, kita dapat meminta AI untuk melakukan simulasi rasionalisasi pilihan jurusan. Kuncinya adalah menyediakan tiga komponen data dalam prompt kita: (1) profil nilai siswa yang sudah dibersihkan, (2) data tren nasional yang bisa kita dapatkan dari portal resmi seperti SNPMB atau dari rilis statistik tahun-tahun sebelumnya, dan (3) data keketatan jurusan di PTN tujuan. Profil nilai siswa menjadi fondasi, karena AI akan menilai basis kompetisi akademiknya. Sementara data tren nasional, seperti jumlah pendaftar, daya tampung, dan rata-rata nilai rapor yang diterima di suatu jurusan dari tahun ke tahun, akan memberikan konteks makro yang sangat berharga.</p>
        <p>Prompting yang efektif tidak sekadar bertanya, "Apakah Budi bisa masuk Teknik Informatika UI?" Pertanyaan seperti itu terlalu sempit dan seringkali hanya menghasilkan jawaban probabilistik generik. Prompt yang kuat harus bersifat analitis dan meminta AI untuk bertindak sebagai seorang analis seleksi perguruan tinggi. Kita bisa memulainya dengan memberikan konteks peran: "Anda adalah seorang analis data penerimaan mahasiswa baru dengan keahlian khusus pada tren SNBP di Indonesia dalam 5 tahun terakhir." Lalu, berikan data profil nilai siswa: "Berikut adalah data nilai siswa bernama [Inisial/Kode Siswa] dari semester 1-5 dalam skala 0-100: [masukkan data]. Hitung rata-rata per semester, tren, dan bandingkan dengan standar nilai yang biasanya berhasil di SNBP." Selanjutnya, sertakan data keketatan jurusan: "Saya akan memberikan data 3 jurusan yang ia minati: [Jurusan A di PTN X, Jurusan B di PTN Y, Jurusan C di PTN Z]. Untuk masing-masing, tingkat keketatan pada tahun lalu adalah 1:45, 1:80, dan 1:120. Berdasarkan data ini, susunlah analisis rasionalisasi yang merangking ketiga pilihan dari yang paling realistis hingga paling challenging, sertakan persentase kemungkinan yang bernuansa, bukan sekadar angka, tetapi dengan alasan yang logis."</p>
        <p>Nilai tambah terbesar dari AI dalam proses ini adalah kemampuannya untuk mensintesis data kuantitatif dengan pertimbangan kualitatif yang lebih luas, menciptakan apa yang bisa disebut sebagai "prediksi naratif". Setelah AI memberikan analisisnya, kita bisa menggali lebih dalam dengan prompt lanjutan yang mempertimbangkan faktor non-akademik: "Faktor lain yang perlu dipertimbangkan: Siswa ini berasal dari daerah X dan memiliki sertifikat juara OSN tingkat provinsi bidang Fisika. Apakah hal ini signifikan mengubah peluangnya untuk pilihan yang highly competitive?" Atau, "Mengingat tren penjurusan di Indonesia, apakah jurusan ini diprediksi akan semakin ketat atau justru menurun peminatnya tahun ini? Bagaimana pengaruh kebijakan baru Kemendikbud tentang lintas jurusan terhadap skema ini?" Dengan cara ini, kita tidak hanya memberi siswa satu jawaban final, melainkan sebuah peta probabilitas yang dinamis. Hasil akhir dari sesi prompting ini bisa kita gunakan sebagai bahan diskusi yang objektif, membantu siswa untuk tidak hanya memilih dengan hati, tetapi juga dengan logika dan strategi. Siswa belajar bahwa memilih jurusan adalah tentang menyelaraskan antara "siapa saya secara akademik" dengan "bagaimana peta persaingannya". Ini mengajarkan mereka informed decision-making, sebuah keterampilan hidup yang jauh melampaui sekadar lolos SNBP.</p>
    </div>
</div>