<!-- 6-6: Menyusun Rekomendasi Jurusan Alternatif yang Underrated namun Memiliki Prospek Tinggi -->
<div class="mb-20">
    <img src="https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&q=80&w=1200" alt="Jurusan underrated" class="w-full h-[400px] md:h-[500px] object-cover rounded-3xl shadow-xl mb-8">
    <h2 class="text-3xl md:text-4xl font-extrabold text-slate-800 mb-6"><i class="fas fa-gem mr-3 text-teal-500"></i>6-6. Menyusun Rekomendasi Jurusan Alternatif yang Underrated namun Memiliki Prospek Tinggi</h2>
    <div class="prose prose-lg prose-slate max-w-none text-slate-600 leading-relaxed">
        <p>Dalam sesi konseling karir, kita seringkali dihadapkan pada fenomena "jurusan favorit": Kedokteran, Teknik Informatika, Hukum, Manajemen, dan Psikologi. Banyak siswa dan orang tua yang terpaku pada jurusan-jurusan ini, mengabaikan fakta bahwa tingkat keketatannya sangat tinggi dan belum tentu cocok dengan potensi unik siswa. Di sinilah peran AI sangat strategis untuk menjadi "pembuka cakrawala". Kita dapat menggunakan AI untuk meracik rekomendasi jurusan alternatif yang underrated—kurang populer di kalangan awam, namun memiliki prospek karir yang sangat cerah, sesuai dengan lanskap ekonomi masa depan, dan seringkali jauh lebih selaras dengan kombinasi minat dan bakat spesifik siswa. Tugas kita sebagai konselor bukanlah menjatuhkan pilihan populer, melainkan memperkenalkan "hidden gems" ini dengan narasi yang kuat dan meyakinkan, didukung oleh data yang AI mampu saring dan sintesis dari berbagai sumber pengetahuan global.</p>
        <p>Kunci prompting untuk topik ini adalah memadukan data profil siswa yang unik dengan data tren industri masa depan. Pertama, kita berikan profil siswa secara ringkas: "Seorang siswa dengan minat kuat pada pelajaran Biologi (terutama isu lingkungan), Geografi, dan memiliki hobi fotografi. Nilai Kimia-nya cukup, tapi ia sangat tidak suka Matematika murni. Secara kepribadian, ia adalah tipe yang suka eksplorasi di alam, detail, dan artistik." Kedua, kita tantang AI untuk keluar dari kotak: "Berikan saya 5 rekomendasi jurusan kuliah yang jarang menjadi pilihan pertama siswa, tapi sebenarnya merupakan titik temu sempurna dari profil ini dan memiliki proyeksi kebutuhan tinggi di masa depan. Untuk setiap jurusan, jelaskan secara naratif: apa yang dipelajari, mengapa cocok dengan profilnya, apa saja profesi yang bisa dituju, dan berikan data atau argumen mengapa prospeknya undervalued (misalnya karena dianggap terlalu spesifik, atau karena berada di fakultas yang kurang populer)." AI mungkin akan memunculkan jurusan seperti Oseanografi, Teknik Geomatika dan Geoinformatika, Rekayasa Kehutanan, Konservasi Sumberdaya Hutan dan Ekowisata, atau Fotografi Sains. Jurusan-jurusan ini jarang terpikirkan, namun sangat relevan.</p>
        <p>Langkah selanjutnya adalah meminta AI untuk menyusun narasi penjualan yang persuasif dan kontekstual untuk Indonesia. Misalnya, untuk jurusan Teknik Geomatika, AI bisa diminta menjelaskan: "Bagaimana jurusan ini berperan penting dalam pembangunan Ibu Kota Nusantara (IKN), proyek smart city, mitigasi bencana di Indonesia, hingga industri pertambangan modern? Ceritakan bagaimana seorang anak yang suka fotografi dan geografi bisa menjadi profesional yang memetakan perubahan garis pantai menggunakan drone dan satelit." Narasi ini sangat penting. Siswa dan orang tua seringkali menolak jurusan alternatif bukan karena prospeknya buruk, tetapi karena mereka tidak bisa "membayangkan" kehidupan kerjanya. AI membantu kita membangun imajinasi tersebut. Untuk setiap jurusan alternatif, kita bisa meminta contoh konkret: "Buatkan profil singkat seorang profesional sukses di bidang ini di Indonesia, jelaskan proyek apa yang sedang ia kerjakan, dan bagaimana ia bisa berkontribusi pada isu lingkungan atau teknologi." Hasilnya adalah sebuah dokumen rekomendasi yang tidak hanya berupa daftar jurusan, melainkan sebuah portofolio naratif yang menghubungkan langsung antara siapa siswa, apa yang akan ia pelajari, dan bagaimana ia akan menjadi bagian dari solusi masa depan. Ini mengubah konseling dari sekadar memberi informasi menjadi menginspirasi panggilan hidup, membuka mata siswa bahwa kesuksesan dan kepuasan karir tidak hanya ada di jalan yang sudah ramai, tetapi juga di jalan setapak yang jarang dilalui.</p>
    </div>
</div>