<!-- 6-2: Teknik Membersihkan dan Menyiapkan Data Nilai Rapor Siswa Semester 1-5 untuk Diinput ke AI -->
<div class="mb-20">
    <img src="https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=1200" alt="Membersihkan data" class="w-full h-[400px] md:h-[500px] object-cover rounded-3xl shadow-xl mb-8">
    <h2 class="text-3xl md:text-4xl font-extrabold text-slate-800 mb-6"><i class="fas fa-broom mr-3 text-emerald-500"></i>6-2. Teknik Membersihkan dan Menyiapkan Data Nilai Rapor Siswa Semester 1-5 untuk Diinput ke AI</h2>
    <div class="prose prose-lg prose-slate max-w-none text-slate-600 leading-relaxed">
        <p>Sebelum kita dapat meminta AI untuk menghasilkan analisis yang cemerlang tentang potensi siswa, kita harus melewati satu tahapan krusial yang seringkali diremehkan: membersihkan dan menyiapkan data. Ibarat seorang juru masak, AI adalah kompor dan peralatan masak yang canggih, tetapi jika bahan-bahan yang kita berikan kotor, busuk, atau tidak seragam, hidangan yang dihasilkan pun akan beracun atau setidaknya tidak lezat. Dalam konteks BK, bahan mentah kita adalah data nilai rapor siswa dari semester 1 hingga 5. Data ini, dalam bentuk aslinya, seringkali tidak siap untuk "dimasak" oleh AI. Masalahnya bisa bermacam-macam: format penulisan mata pelajaran yang berubah-ubah (misal: "B. Indonesia" di satu semester, "Bahasa Indonesia" di semester lain), nilai yang ditulis dengan format berbeda (angka 80 vs. delapan puluh), adanya nilai yang kosong karena siswa sakit saat ujian, atau penggabungan nilai pengetahuan dan keterampilan yang perlu dipisahkan. Teknik membersihkan data ini pada dasarnya adalah proses standardisasi, validasi, dan transformasi data agar AI dapat membacanya secara konsisten, sehingga pola yang ditemukan nantinya adalah pola asli dari performa siswa, bukan pola dari kekacauan data.</p>
        <p>Langkah pertama dan paling vital adalah standardisasi entitas dan format. Bayangkan Anda menyusun data untuk satu angkatan yang terdiri dari 200 siswa, diambil dari database sekolah yang berbeda-beda formatnya antar semester. Kita perlu memastikan bahwa nama mata pelajaran untuk setiap siswa dan setiap semester adalah persis sama. "Matematika (Umum)" dan "Matematika Wajib" harus diputuskan menjadi satu nama yang seragam, misalnya "Matematika". Proses ini bisa sangat melelahkan jika dilakukan manual, namun kita bisa menggunakan fitur "Find & Replace" di Excel atau Google Sheets. Selanjutnya, format nilai. AI bekerja paling baik dengan data numerik. Jadi, pastikan semua nilai akhir diubah menjadi angka dengan skala yang sama, idealnya skala 0-100. Hapus semua karakter non-numerik seperti koma, titik, atau keterangan tambahan seperti "80 (Tuntas)". Jika ada nilai yang berupa huruf (A, B, C), konversikan ke rentang numerik yang disepakati secara konsisten. Untuk data yang kosong, kita harus memutuskan strategi: apakah akan diisi dengan rata-rata nilai siswa itu di semester lain, atau ditandai dengan kode khusus (misalnya "9999") agar AI tahu bahwa itu adalah data yang tidak tersedia dan bukan nol murni. Keputusan ini penting karena akan memengaruhi interpretasi AI terhadap riwayat akademik siswa.</p>
        <p>Setelah data bersih dan seragam, langkah berikutnya adalah menata struktur data agar AI mampu membacanya sebagai sebuah perjalanan waktu. Format yang paling mudah dan ampuh adalah format tabel "lebar" (wide format) di spreadsheet, di mana setiap baris mewakili satu siswa, dan setiap kolom mewakili satu mata pelajaran di satu semester tertentu. Contoh kolomnya: Nama_Siswa, Mat_S1, Mat_S2, Mat_S3, Fis_S1, Fis_S2, dst. Struktur ini memungkinkan AI untuk dengan mudah melacak perubahan nilai per mata pelajaran dari waktu ke waktu. Sebelum menginput ke AI, data ini harus sudah dalam bentuk teks yang terstruktur. Kita bisa menyalin sebagian kecil data (misal 5-10 siswa) ke dalam prompt kita sebagai contoh. Namun, ada satu hal lagi yang sangat penting: anonimisasi. Sebagai konselor, kita terikat kode etik kerahasiaan. Gantilah nama asli siswa dengan inisial atau kode ID seperti "Siswa_01", "Siswa_02". Jangan pernah mengunggah data lengkap siswa dengan nama asli dan nomor induk ke platform AI publik yang belum terjamin keamanan datanya. Data yang sudah dibersihkan, terstruktur, dan teranonimisasi inilah yang siap menjadi "bahan bakar" untuk menghasilkan prediksi dan insight. Dengan menyiapkan data secara cermat, kita tidak hanya membuat AI bekerja lebih efektif, tetapi juga sedang melakukan proses refleksi profesional sebagai konselor; kita menata ulang cara kita memandang perjalanan akademik setiap siswa dalam bentuk yang paling murni.</p>
    </div>
</div>