<!-- 6-7: Menyusun Rencana Cadangan (Plan B) Terarah untuk Persiapan SNBT/Ujian Mandiri -->
<div class="mb-20">
    <img src="https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=80&w=1200" alt="Plan B" class="w-full h-[400px] md:h-[500px] object-cover rounded-3xl shadow-xl mb-8">
    <h2 class="text-3xl md:text-4xl font-extrabold text-slate-800 mb-6"><i class="fas fa-map-signs mr-3 text-orange-500"></i>6-7. Menyusun Rencana Cadangan (Plan B) Terarah untuk Persiapan SNBT/Ujian Mandiri</h2>
    <div class="prose prose-lg prose-slate max-w-none text-slate-600 leading-relaxed">
        <p>Menemani siswa mempersiapkan diri untuk SNBT (Seleksi Nasional Berdasarkan Tes) atau ujian mandiri adalah tentang membangun ketahanan mental dan strategi. Seringkali, siswa begitu terpaku pada satu tujuan SNBP yang belum tentu lolos, sehingga ketika gagal, mereka mengalami disorientasi dan kehilangan momentum. Di sinilah kita, guru BK, perlu turun tangan untuk memfasilitasi penyusunan "Plan B" yang tidak sekadar menjadi pelarian, melainkan sebuah jalur alternatif yang sama terhormat dan terencananya. AI dapat menjadi mitra brainstorming yang hebat dalam proses ini. Ia mampu mengolah data kegagalan sebagai input netral, mencocokkannya dengan ribuan opsi skema seleksi dan jurusan, lalu menghasilkan peta jalan baru yang personal, realistis, dan tetap sejalan dengan minat bakat siswa. Kuncinya adalah membangun narasi bahwa Plan B bukanlah "rencana pecundang", melainkan "rencana navigator" yang menunjukkan bahwa ada banyak rute menuju destinasi yang sama atau bahkan destinasi yang lebih baik.</p>
        <p>Proses prompting dimulai dengan melakukan "otopsi positif" terhadap hasil SNBP. Ajarkan siswa untuk tidak melihat kegagalan sebagai vonis final, melainkan sebagai data. Berikan prompt ke AI: "Seorang siswa dengan profil nilai [deskripsikan] tidak lolos SNBP di jurusan Teknik Sipil Universitas A. Analisis komponen nilai yang mungkin menjadi penyebab (apakah nilai Matematika yang kurang kompetitif, ataukah komponen lain?). Sekarang, dengan bekal data bahwa ia memiliki kekuatan di Fisika dan Matematika terapan, susunlah tiga Plan B paralel yang mencakup tiga jalur berbeda: (1) SNBT di PTN lain dengan jurusan yang serupa tapi lebih realistis tingkat keketatannya, (2) Ujian Mandiri di PTN yang sama tapi dengan jurusan 'kembaran' yang masih satu rumpun keilmuan, dan (3) Jalur vokasi atau politeknik dengan prospek kerja cepat yang terkait dengan keahliannya." AI kemudian akan menyajikan analisis komparatif, misalnya antara SNBT Teknik Sipil Universitas B dengan Ujian Mandiri D4 Teknik Konstruksi Gedung di politeknik terkemuka, lengkap dengan perbandingan materi ujian, daya tampung, dan proyeksi karir lulusannya.</p>
        <p>Yang tak kalah penting, AI dapat membantu menyusun strategi belajar yang terfokus untuk setiap Plan B tersebut. Setiap jalur seleksi—SNBT, Ujian Mandiri PTN A, Ujian Mandiri PTN B—seringkali memiliki format dan materi ujian yang berbeda. Prompt lanjutannya bisa sangat taktis: "Buatkan breakdown materi ujian untuk ketiga opsi di atas. Identifikasi irisan materi yang bisa dipelajari bersamaan (untuk efisiensi waktu) dan materi spesifik yang hanya muncul di satu ujian saja. Susun timeline belajar 2 bulan yang membagi fokus secara proporsional, dengan asumsi siswa ini lebih kuat di Fisika daripada Kimia." Hasilnya adalah sebuah rencana belajar yang terpersonalisasi. Lebih jauh lagi, kita bisa meminta AI untuk membantu membangun mental bertanding siswa untuk jalur mandiri yang seringkali lebih menegangkan. Minta AI untuk membuat simulasi skenario wawancara atau tips menghadapi soal-soal khas ujian mandiri yang lebih konseptual. Dengan memiliki Plan B yang detail, terstruktur, dan tetap memberi ruang bagi minatnya, siswa akan merasa lebih aman dan berdaya. Mereka belajar bahwa tujuan akhir bukanlah nama kampus, melainkan penguasaan kompetensi. Ini adalah pelajaran hidup tentang resiliensi, fleksibilitas, dan perencanaan strategis yang akan sangat berguna dalam perjalanan karir mereka nanti. Plan B yang baik adalah yang ketika dijalani, tidak terasa seperti pilihan kedua.</p>
    </div>
</div>