
<!-- 6-5: Merancang Pertanyaan Tes Minat Bakat (Holland Code/RIASEC) Sederhana dengan AI -->
<div class="mb-20">
    <img src="https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&q=80&w=1200" alt="Tes minat bakat" class="w-full h-[400px] md:h-[500px] object-cover rounded-3xl shadow-xl mb-8">
    <h2 class="text-3xl md:text-4xl font-extrabold text-slate-800 mb-6"><i class="fas fa-puzzle-piece mr-3 text-indigo-500"></i>6-5. Merancang Pertanyaan Tes Minat Bakat (Holland Code/RIASEC) Sederhana dengan AI</h2>
    <div class="prose prose-lg prose-slate max-w-none text-slate-600 leading-relaxed">
        <p>Teori Holland Code, atau RIASEC (Realistic, Investigative, Artistic, Social, Enterprising, Conventional), adalah salah satu fondasi utama dalam bimbingan karir. Namun, instrumen tes formalnya seringkali berbayar, panjang, dan menggunakan bahasa yang kurang kontekstual dengan keseharian siswa Indonesia. Di sinilah AI hadir bukan untuk menggantikan psikolog atau alat tes yang tervalidasi, melainkan untuk menjadi "pabrik pertanyaan" yang dinamis dan personal. Kita dapat menggunakan AI untuk merancang serangkaian pertanyaan eksplorasi minat bakat yang mudah dipahami, relevan secara budaya, dan bisa langsung digunakan dalam sesi konseling. Tujuannya bukanlah untuk memberikan skor akhir yang kaku seperti "kamu adalah tipe Artistic", melainkan untuk membuka dialog, menyentuh kesadaran diri siswa tentang preferensi kerjanya, dan memberikan spektrum warna minat yang lebih kaya. Dengan AI, kita bisa menciptakan pertanyaan yang tidak hanya bertanya "apa yang kamu suka?", tetapi juga "bagaimana caramu menyelesaikan masalah?", "dalam situasi seperti apa kamu merasa paling berenergi?", dan "peran apa yang secara alami kamu ambil dalam kelompok?", yang semuanya merupakan indikator kuat dari tipe RIASEC.</p>
        <p>Proses merancangnya dimulai dengan memberikan perintah (prompt) yang sangat spesifik kepada AI. Kita bisa mengatakan: "Buatkan saya 20 pertanyaan situasional sederhana untuk mengidentifikasi minat dan bakat siswa SMA menggunakan kerangka Holland Code (RIASEC). Setiap pertanyaan harus menggambarkan sebuah skenario yang dekat dengan kehidupan remaja Indonesia, bukan dunia kerja profesional. Untuk setiap pertanyaan, sediakan 3 pilihan jawaban yang masing-masing merepresentasikan satu kode Holland yang berbeda. Jangan menyebutkan label kode Holland-nya di depan siswa, simpan sebagai kunci jawaban untuk guru BK." Contoh output yang mungkin dihasilkan AI: "Saat ada tugas kelompok membuat proyek daur ulang sampah, bagian mana yang paling membuatmu bersemangat? A. Merancang dan membangun langsung model fisiknya dari barang bekas (Realistic). B. Meneliti data tentang jenis sampah dan efektivitas daur ulang (Investigative). C. Membuat konsep kampanye dan poster ajakan untuk warga sekolah (Artistic)." Keunggulan pertanyaan semacam ini adalah ia menyelami minat melalui aksi dan pilihan konkret, bukan melalui pertanyaan abstrak seperti "Apakah kamu suka bekerja dengan data?" yang seringkali membingungkan siswa. Kita bisa meminta AI untuk memvariasikan tema, mulai dari skenario di kelas, keluarga, organisasi, hingga media sosial, sehingga mencakup semua lini kehidupan remaja.</p>
        <p>Agar lebih canggih dan personal, AI bisa kita minta untuk mengaitkan hasil "tes" sederhana ini dengan data akademik yang sudah kita miliki. Prompt lanjutannya bisa seperti: "Berdasarkan data pilihan jawaban siswa bernama [Inisial] pada tes tadi, ia cenderung memilih jawaban yang merepresentasikan kode Social, Artistic, dan Investigative, dengan sangat sedikit pada kode Conventional. Sekarang, gabungkan profil ini dengan data nilainya yang menunjukkan keunggulan di Biologi dan Sosiologi, serta kelemahan di Akuntansi. Berikan saya tiga rekomendasi karir atau jurusan kuliah yang unik, yang merupakan titik temu antara minat RIASEC-nya dan kekuatan akademiknya." AI mungkin akan merekomendasikan profesi seperti Terapis Okupasi (Social+Investigative), Jurnalis Sains (Artistic+Investigative+Social), atau Spesialis CSR Perusahaan (Social+Artistic). Kekuatan sejati dari pendekatan ini adalah kita tidak memperlakukan hasil RIASEC sebagai kotak yang membatasi, melainkan sebagai batu loncatan untuk eksplorasi lebih dalam. Siswa diajak untuk melihat bahwa kombinasi minat mereka itu unik, dan bahwa di dunia nyata, profesi yang sukses seringkali adalah perpaduan dari dua atau tiga kode. Ini adalah pesan yang jauh lebih memberdayakan daripada sekadar label "kamu tipe Sosial".</p>
    </div>
</div>