<!-- 9-10: Debat Terbuka Kelas: Menavigasi Masa Depan Pekerjaan dan Skill Apa yang Paling Dibutuhkan Siswa -->
<div class="mb-20">
    <img src="https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&q=80&w=1200" alt="Debat masa depan" class="w-full h-[400px] md:h-[500px] object-cover rounded-3xl shadow-xl mb-8">
    <h2 class="text-3xl md:text-4xl font-extrabold text-slate-800 mb-6"><i class="fas fa-chalkboard-user mr-3 text-teal-500"></i>9-10. Debat Terbuka Kelas: Menavigasi Masa Depan Pekerjaan dan Skill Apa yang Paling Dibutuhkan Siswa</h2>
    <div class="prose prose-lg prose-slate max-w-none text-slate-600 leading-relaxed">
        <p>Masa depan pekerjaan akan sangat berbeda karena AI mengotomatisasi banyak tugas rutin. Siswa Gen-Z dan Alfa perlu mempersiapkan skill yang tidak dapat digantikan AI: kreativitas, berpikir kritis, kecerdasan emosional, empati, kolaborasi, dan kemampuan belajar sepanjang hayat. Debat terbuka kelas adalah strategi efektif untuk melibatkan siswa mendiskusikan masa depan pekerjaan, skill yang paling dibutuhkan, dan bagaimana mereka mempersiapkan diri. Debat terbuka juga melatih keterampilan berargumen, mendengarkan, dan berpikir kritis.</p>
        <p>Topik debat terbuka yang relevan: (1) "Apakah AI akan menggantikan pekerjaan guru?" (2) "Skill apa yang paling penting untuk dipelajari di era AI?" (3) "Apakah sekolah saat ini sudah mempersiapkan siswa untuk masa depan AI?" (4) "Seharusnya AI dilarang atau diintegrasikan di sekolah?" (5) "Pekerjaan apa yang akan hilang dan pekerjaan apa yang akan muncul di 20 tahun ke depan?" Guru memfasilitasi debat dengan memastikan semua suara terdengar, argumen berbasis fakta, dan suasana tetap hormat.</p>
        <p>Contoh struktur debat terbuka kelas: Pembukaan Guru: "Hari ini kita akan debat tentang masa depan pekerjaan di era AI. Tidak ada jawaban benar/salah; yang penting adalah argumen yang berbasis fakta dan saling menghargai." Topik 1: "Apakah AI akan menggantikan pekerjaan guru?" – Tim Pro: "AI bisa menggantikan guru dalam menyampaikan materi faktual, membuat kuis, dan memberikan feedback otomatis." – Tim Kontra: "AI tidak bisa menggantikan empati, motivasi, dan hubungan manusia yang dibangun guru dengan siswa." Topik 2: "Skill apa yang paling penting untuk dipelajari?" – Kreativitas, berpikir kritis, kecerdasan emosional, kolaborasi, literasi AI, learning agility. Penutup Guru: "Terima kasih atas argumen yang luar biasa. Intinya: AI adalah alat, bukan pengganti manusia. Skill yang paling berharga adalah yang membuat kita lebih manusiawi." Dengan debat terbuka kelas, siswa mempersiapkan diri untuk masa depan pekerjaan, mengembangkan keterampilan kritis, dan menemukan arah karir mereka.</p>
    </div>
</div>