<!-- 9-4: Mendesain Penugasan "Kebal AI": Merancang Tugas Berbasis Observasi Fisik, Wawancara, dan Empati -->
<div class="mb-20">
    <img src="https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&q=80&w=1200" alt="Tugas kebal AI" class="w-full h-[400px] md:h-[500px] object-cover rounded-3xl shadow-xl mb-8">
    <h2 class="text-3xl md:text-4xl font-extrabold text-slate-800 mb-6"><i class="fas fa-shield-virus mr-3 text-green-500"></i>9-4. Mendesain Penugasan "Kebal AI": Merancang Tugas Berbasis Observasi Fisik, Wawancara, dan Empati</h2>
    <div class="prose prose-lg prose-slate max-w-none text-slate-600 leading-relaxed">
        <p>Tugas "kebal AI" adalah tugas yang tidak dapat diselesaikan hanya dengan copy-paste dari AI karena memerlukan pengalaman fisik, interaksi manusia, atau refleksi emosional yang unik. Tugas berbasis observasi fisik memaksa siswa keluar dari rumah dan mengamati lingkungan nyata. Tugas wawancara mengharuskan siswa berinteraksi dengan orang lain dan mencatat perspektif unik. Tugas berbasis empati memerlukan siswa merefleksikan perasaan, pengalaman pribadi, atau hubungan dengan orang lain yang tidak dapat digantikan AI.</p>
        <p>Contoh penugasan kebal AI: "Observasi fisik: Kunjungi pasar tradisional, catat 5 interaksi antara penjual dan pembeli, lalu tulis refleksi tentang dinamika sosial yang kamu lihat." – "Wawancara: Wawancarai 3 orang dewasa tentang perubahan teknologi dalam hidup mereka, lalu bandingkan perspektif mereka dengan generasimu." – "Empati: Tulis surat untuk orang tua/guru tentang satu hal yang kamu hargai dari mereka, sertakan memori spesifik yang tidak bisa dibagikan ke orang lain." – "Refleksi pribadi: Ceritakan momen saat kamu gagal dalam belajar, bagaimana perasaanmu, dan apa yang kamu pelajari dari kegagalan itu."</p>
        <p>Dengan tugas kebal AI, guru memastikan siswa belajar dari pengalaman nyata, melatih keterampilan sosial, dan menghasilkan karya yang autentik. Tugas seperti ini juga mengembangkan kecerdasan emosional dan empati siswa, dua kompetensi yang sangat penting di era AI. Ketika siswa tahu bahwa tugas mereka tidak bisa "dikerjakan" oleh AI, mereka lebih termotivasi untuk terlibat langsung, bertanya, dan berefleksi. Ini adalah cara paling efektif untuk mengatasi copy-paste AI sekaligus membangun keterampilan abad ke-21.</p>
    </div>
</div>