<!-- 9-3: Anatomi AI Detector: Kelebihan, Kekurangan, dan Bahaya Tuduhan False-Positive pada Siswa -->
<div class="mb-20">
    <img src="https://images.unsplash.com/photo-1555949963-aa79dcee981c?auto=format&fit=crop&q=80&w=1200" alt="AI detector" class="w-full h-[400px] md:h-[500px] object-cover rounded-3xl shadow-xl mb-8">
    <h2 class="text-3xl md:text-4xl font-extrabold text-slate-800 mb-6"><i class="fas fa-microscope mr-3 text-purple-500"></i>9-3. Anatomi AI Detector: Kelebihan, Kekurangan, dan Bahaya Tuduhan False-Positive pada Siswa</h2>
    <div class="prose prose-lg prose-slate max-w-none text-slate-600 leading-relaxed">
        <p>AI detector adalah alat yang dirancang untuk mendeteksi apakah tulisan dibuat oleh AI atau manusia. Alat ini bekerja dengan menganalisis pola statistik seperti keragaman kata, struktur kalimat, dan "perplexity" (tingkat ketidakpastian prediksi kalimat). Namun, AI detector tidak sempurna: banyak menghasilkan false-positive (menuduh tulisan manusia sebagai AI) dan false-negative (gagal mendeteksi tulisan AI). Menggunakan AI detector sebagai satu-satunya bukti untuk menuduh siswa menyontek adalah praktik berbahaya yang dapat merusak kepercayaan dan hubungan guru-siswa.</p>
        <p>Kelebihan AI detector: cepat, objektif secara statistik, dan dapat menjadi indikator awal untuk investigasi lebih lanjut. Kekurangan: tidak akurat 100%, rentan bias terhadap tulisan yang formal atau terstruktur, dan tidak dapat membedakan antara tulisan yang diparafrase secara etis dengan tulisan yang plagiat. Bahaya false-positive sangat serius: siswa yang tidak bersalah bisa dituduh menyontek, kehilangan motivasi, dan merasa tidak dipercaya oleh guru. Guru harus sangat hati-hati sebelum menggunakan hasil AI detector sebagai dasar sanksi.</p>
        <p>Contoh penggunaan AI detector yang bijak: "AI detector menunjukkan 70% kemungkinan tulisan ini dari AI. Ini bukan bukti final, tapi saya ingin diskusi dengan kamu tentang proses menulis tugasmu." – "Saya tidak akan menghukummu hanya berdasarkan AI detector. Mari kita lihat proses kerjamu: draft, revisi, dan bagaimana kamu mengembangkan ide." – "AI detector bisa salah. Jika kamu yakin tulisan ini murni kamu, tunjukkan bukti proses: catatan, draft, atau rekaman brainstorming." – "Saya menggunakan AI detector hanya sebagai alat bantu, bukan sebagai hakim. Keputusan final saya berdasarkan dialog dan bukti proses, bukan hanya skor detector." Dengan memahami anatomi dan keterbatasan AI detector, guru menghindari tuduhan false-positive dan menjaga kepercayaan dengan siswa.</p>
    </div>
</div>