<!-- 9-1: Psikologi Gen-Z & Alfa: Memahami Alasan dan Cara Siswa Memanfaatkan AI untuk Mengerjakan Tugas -->
<div class="mb-20">
    <img src="https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&q=80&w=1200" alt="Gen Z dan AI" class="w-full h-[400px] md:h-[500px] object-cover rounded-3xl shadow-xl mb-8">
    <h2 class="text-3xl md:text-4xl font-extrabold text-slate-800 mb-6"><i class="fab fa-react mr-3 text-blue-500"></i>9-1. Psikologi Gen-Z & Alfa: Memahami Alasan dan Cara Siswa Memanfaatkan AI untuk Mengerjakan Tugas</h2>
    <div class="prose prose-lg prose-slate max-w-none text-slate-600 leading-relaxed">
        <p>Gen-Z (lahir 1997–2012) dan Alfa (lahir 2013–sekarang) adalah generasi yang tumbuh bersama teknologi digital sejak lahir. Bagi mereka, AI bukan alat asing, melainkan teman sehari-hari yang memudahkan hidup, termasuk dalam menyelesaikan tugas sekolah. Siswa menggunakan AI bukan selalu karena malas, tetapi karena mereka melihat AI sebagai solusi efisien untuk menghemat waktu, mengurangi beban kognitif, atau mengatasi kesulitan memahami materi. Memahami motivasi ini penting agar guru tidak langsung menghakimi, tetapi justru membimbing siswa menggunakan AI secara bertanggung jawab.</p>
        <p>Cara siswa memanfaatkan AI sangat beragam: ada yang menggunakan untuk brainstorming ide, ada yang untuk merangkum teks panjang, ada yang untuk mengecek tata bahasa, dan ada juga yang untuk menulis seluruh tugas dari awal. Siswa Gen-Z dan Alfa cenderung lebih nyaman bertanya ke AI daripada ke guru karena AI tidak menghakimi, selalu tersedia 24/7, dan memberikan jawaban instan. Namun, ketergantungan berlebihan pada AI berisiko mengurangi kemampuan berpikir kritis, kreativitas, dan keterampilan menulis mandiri siswa.</p>
        <p>Contoh cara siswa menggunakan AI: "Saya tanya ChatGPT untuk buatkan kerangka makalah dulu, baru saya kembangkan sendiri." – "Saya pakai AI untuk rangkum artikel 10 halaman jadi 1 halaman biar lebih cepat paham." – "Saya copy-paste semua tugas ke AI karena ternyata lebih cepat dan saya tidak habis waktu." – "Saya minta AI koreksi grammar tulisan saya sebelum submit ke guru." Dengan memahami psikologi dan cara siswa menggunakan AI, guru dapat merespon lebih empatik, mendidik, dan mengarahkan penggunaan AI yang etis dan konstruktif.</p>
    </div>
</div>