<!-- 9-2: Mitigasi Risiko: Cara Cerdas Mengatasi "Tsunami" Tugas Hasil Copy-Paste Mentah dari ChatGPT -->
<div class="mb-20">
    <img src="https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=1200" alt="Tsunami tugas AI" class="w-full h-[400px] md:h-[500px] object-cover rounded-3xl shadow-xl mb-8">
    <h2 class="text-3xl md:text-4xl font-extrabold text-slate-800 mb-6"><i class="fas fa-water mr-3 text-cyan-500"></i>9-2. Mitigasi Risiko: Cara Cerdas Mengatasi "Tsunami" Tugas Hasil Copy-Paste Mentah dari ChatGPT</h2>
    <div class="prose prose-lg prose-slate max-w-none text-slate-600 leading-relaxed">
        <p>"Tsunami" tugas hasil copy-paste mentah dari ChatGPT adalah tantangan nyata yang dihadapi guru saat ini. Banyak siswa mengirimkan tugas yang jelas-jelas ditulis AI: bahasa terlalu formal, struktur kaku, tidak ada suara pribadi, dan kadang bahkan salah fakta. Menghukum siswa secara langsung bukan solusi terbaik karena tidak mengajarkan mereka belajar dari kesalahan. Strategi mitigasi yang cerdas adalah mencegah, mendeteksi dengan bijak, dan mengedukasi siswa tentang penggunaan AI yang bertanggung jawab.</p>
        <p>Cara mengatasi tugas copy-paste AI dimulai dengan pencegahan: rancang tugas yang sulit di-copy-paste (misalnya tugas berbasis observasi fisik, wawancara, atau refleksi pribadi). Saat mendeteksi tugas AI, jangan langsung menuduh; lakukan dialog dengan siswa, minta mereka menjelaskan isi tugas, atau minta mereka merevisi dengan menambahkan suara pribadi. Guru juga dapat mengajar siswa cara mendeteksi apakah tulisan mereka terdengar seperti AI, lalu merevisi sendiri. Pendekatan edukatif lebih efektif daripada pendekatan hukuman.</p>
        <p>Contoh strategi mitigasi: "Sebelum submit, coba baca ulang tulisannya. Apakah ini terdengar seperti suara kamu sendiri? Jika tidak, revisi dengan menambahkan pengalaman pribadi." – "Saya bisa lihat tulisan ini sangat formal dan tidak ada contoh pribadi. Mari kita diskusikan bagaimana kamu bisa memasukkan pengalamanmu ke dalam tugas ini." – "Tugas berikutnya akan saya rancang agar lebih personal: kamu harus wawancara 3 orang dan tulis refleksi sendiri. AI tidak bisa menggantikan pengalamanmu." – "Jika kamu pakai AI, catat di bagian akhir: 'Saya menggunakan AI untuk [tujuan apa], lalu saya revisi dengan [apa yang saya tambahkan].' Ini transparansi yang saya hargai." Dengan strategi mitigasi yang cerdas dan edukatif, guru mengurangi tugas copy-paste AI tanpa merusak hubungan dengan siswa.</p>
    </div>
</div>