<!-- 9-7: Mengajarkan Literasi AI Kepada Siswa: Membimbing Mereka Menjadi Pengguna yang Kritis dan Beretika -->
<div class="mb-20">
    <img src="https://images.unsplash.com/photo-1488190211105-8b0e65b80b4e?auto=format&fit=crop&q=80&w=1200" alt="Literasi AI" class="w-full h-[400px] md:h-[500px] object-cover rounded-3xl shadow-xl mb-8">
    <h2 class="text-3xl md:text-4xl font-extrabold text-slate-800 mb-6"><i class="fas fa-graduation-cap mr-3 text-red-500"></i>9-7. Mengajarkan Literasi AI Kepada Siswa: Membimbing Mereka Menjadi Pengguna yang Kritis dan Beretika</h2>
    <div class="prose prose-lg prose-slate max-w-none text-slate-600 leading-relaxed">
        <p>Literasi AI adalah keterampilan esensial di era digital: siswa perlu memahami apa itu AI, bagaimana AI bekerja, apa kemampuan dan keterbatasannya, serta bagaimana menggunakan AI secara etis. Mengajarkan literasi AI bukan hanya tentang cara menggunakan tools, tetapi tentang berpikir kritis terhadap output AI, mengidentifikasi bias, dan memahami dampak sosial dari penggunaan AI. Siswa yang literat AI akan menjadi pengguna yang bertanggung jawab, bukan sekadar konsumen pasif.</p>
        <p>Konten pembelajaran literasi AI: (1) dasar-dasar AI: apa itu machine learning, bagaimana AI belajar dari data; (2) kemampuan dan keterbatasan AI: apa yang bisa dan tidak bisa dilakukan AI; (3) bias algoritma: bagaimana AI dapat mereproduksi rasisme, seksisme, atau stereotip dari data training; (4) etika penggunaan AI: kapan boleh, kapan tidak, dan bagaimana melaporkan penggunaan AI; (5) keamanan data: jangan bagikan info pribadi ke AI. Guru dapat mengajarkan literasi AI melalui diskusi, studi kasus, atau proyek kecil.</p>
        <p>Contoh aktivitas pembelajaran literasi AI: "Diskusi: Coba berikan prompt yang sama ke 3 AI berbeda. Bandingkan hasilnya. Apa yang sama, apa yang berbeda, dan mengapa?" – "Studi kasus: AI memberikan jawaban yang bias terhadap perempuan. Identifikasi biasnya, diskusikan dampaknya, dan bagaimana kamu bisa mengkritik output AI ini." – "Proyek: Buat panduan penggunaan AI yang etis untuk teman sekelas kamu. Sertakan contoh do's dan don'ts." – "Refleksi: Saat kamu menggunakan AI, apa yang kamu periksa sebelum percaya dengan output AI? Bagaimana kamu memastikan informasi itu akurat?" Dengan mengajarkan literasi AI, guru membekali siswa dengan keterampilan kritis dan etis untuk menghadapi dunia yang semakin didominasi AI.</p>
    </div>
</div>