<!-- 9-5: Menyusun SOP dan Kebijakan Penggunaan AI yang Adil dan Transparan di Lingkungan Sekolah -->
<div class="mb-20">
    <img src="https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&q=80&w=1200" alt="SOP AI sekolah" class="w-full h-[400px] md:h-[500px] object-cover rounded-3xl shadow-xl mb-8">
    <h2 class="text-3xl md:text-4xl font-extrabold text-slate-800 mb-6"><i class="fas fa-file-contract mr-3 text-indigo-500"></i>9-5. Menyusun SOP dan Kebijakan Penggunaan AI yang Adil dan Transparan di Lingkungan Sekolah</h2>
    <div class="prose prose-lg prose-slate max-w-none text-slate-600 leading-relaxed">
        <p>Kebijakan penggunaan AI di sekolah yang adil dan transparan penting untuk menciptakan lingkungan belajar yang etis dan konsisten. SOP (Standard Operating Procedure) yang jelas membantu guru dan siswa memahami apa yang diperbolehkan, apa yang dilarang, dan konsekuensi jika melanggar. Kebijakan yang adil tidak melarang AI sepenuhnya, tetapi mengatur cara penggunaannya secara bertanggung jawab. Transparansi berarti sekolah mengomunikasikan kebijakan dengan jelas ke semua pemangku kepentingan: guru, siswa, orang tua, dan masyarakat.</p>
        <p>Langkah menyusun SOP penggunaan AI: (1) bentuk tim kecil (guru, perwakilan siswa, konselor) untuk merumuskan kebijakan; (2) diskusikan tujuan: mengapa AI perlu diatur, apa risiko, dan apa manfaat; (3) rumuskan aturan jelas: kapan AI boleh digunakan, kapan tidak, dan bagaimana melaporkan penggunaan AI; (4) buat konsekuensi bertahap untuk pelanggaran: peringatan, revisi tugas, hingga sanksi akademis; (5) komunikasikan kebijakan ke semua pihak dan tinjau ulang secara berkala.</p>
        <p>Contoh kebijakan penggunaan AI: "AI boleh digunakan untuk brainstorming ide, merangkum, atau mengecek tata bahasa, tetapi tidak untuk menulis seluruh tugas dari awal." – "Jika kamu menggunakan AI, kamu harus mencantumkan di bagian akhir: 'Saya menggunakan AI untuk [tujuan], lalu saya revisi dengan [apa yang saya tambahkan].'" – "Tugas yang dilarang menggunakan AI: reflective journal, wawancara, observasi fisik, dan tugas yang mensyaratkan suara pribadi." – "Pelanggaran pertama: peringatan dan revisi tugas. Pelanggaran kedua: nilai tugas 0. Pelanggaran ketiga: eskalasi ke kepala sekolah." Dengan SOP yang adil dan transparan, sekolah menciptakan budaya penggunaan AI yang etis, bertanggung jawab, dan mendukung pembelajaran.</p>
    </div>
</div>