<!-- 9-8: Diskusi Bias Algoritma: Menyadarkan Siswa tentang Bahaya Rasisme/Seksisme yang Tersembunyi dalam AI -->
<div class="mb-20">
    <img src="https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&q=80&w=1200" alt="Bias algoritma" class="w-full h-[400px] md:h-[500px] object-cover rounded-3xl shadow-xl mb-8">
    <h2 class="text-3xl md:text-4xl font-extrabold text-slate-800 mb-6"><i class="fas fa-balance-scale mr-3 text-orange-500"></i>9-8. Diskusi Bias Algoritma: Menyadarkan Siswa tentang Bahaya Rasisme/Seksisme yang Tersembunyi dalam AI</h2>
    <div class="prose prose-lg prose-slate max-w-none text-slate-600 leading-relaxed">
        <p>AI tidak netral; AI belajar dari data yang dibuat manusia, dan data manusia sering mengandung bias rasisme, seksisme, homofobia, atau stereotip lainnya. Ketika AI menghasilkan output yang bias, siswa perlu disadarkan bahwa ini bukan kesalahan teknis belaka, tetapi cerminan ketidakadilan sosial yang sudah ada. Mengajarkan siswa tentang bias algoritma penting untuk membangun kesadaran kritis, empati, dan tanggung jawab sosial. Siswa harus belajar mengkritik AI, bukan hanya menerima outputnya secara pasif.</p>
        <p>Contoh bias algoritma dalam AI: (1) AI menghasilkan gambar dokter selalu pria, perawat selalu wanita; (2) AI memberikan saran karier yang bias terhadap gender; (3) AI menerjemahkan kata netral gender menjadi bias gender; (4) AI memberikan respons yang lebih sopan ke nama tertentu daripada yang lain. Guru dapat menunjukkan contoh konkret bias ini ke siswa, lalu memfasilitasi diskusi tentang dampak sosialnya dan bagaimana mengkritik/menghindari bias tersebut.</p>
        <p>Contoh aktivitas diskusi bias algoritma: "Coba prompt: 'Gambar seorang pemimpin.' Lihat hasilnya. Apakah semua pemimpin terlihat seperti gender/etnis tertentu? Mengapa ini bermasalah?" – "Coba prompt: 'Dia adalah dokter. Apa yang dia lakukan?' AI mungkin menggunakan kata 'dia' sebagai pria. Ini menunjukkan bias gender. Bagaimana kamu bisa mengkritik ini?" – "Diskusi: Apa dampaknya jika generasi muda selalu melihat stereotip ini dari AI? Bagaimana ini membentuk persepsi mereka tentang dunia?" – "Proyek: Cari 3 contoh bias dalam output AI, jelaskan biasnya, dampaknya, dan bagaimana AI bisa diperbaiki." Dengan diskusi bias algoritma, siswa menjadi lebih kritis terhadap AI dan lebih sadar akan ketidakadilan sosial yang tersembunyi.</p>
    </div>
</div>
