<!-- 9-9: Plagiarisme 2.0: Mendefinisikan Ulang Makna "Menyontek" dan "Karya Asli" di Era Generative AI -->
<div class="mb-20">
    <img src="https://images.unsplash.com/photo-1589998059171-988d887df646?auto=format&fit=crop&q=80&w=1200" alt="Plagiarisme 2.0" class="w-full h-[400px] md:h-[500px] object-cover rounded-3xl shadow-xl mb-8">
    <h2 class="text-3xl md:text-4xl font-extrabold text-slate-800 mb-6"><i class="fas fa-copyright mr-3 text-pink-500"></i>9-9. Plagiarisme 2.0: Mendefinisikan Ulang Makna "Menyontek" dan "Karya Asli" di Era Generative AI</h2>
    <div class="prose prose-lg prose-slate max-w-none text-slate-600 leading-relaxed">
        <p>Di era generative AI, definisi tradisional tentang "menyontek" dan "karya asli" menjadi kabur. Jika siswa menggunakan AI untuk brainstorming ide, apakah itu menyontek? Jika siswa memparafrase output AI, apakah itu karya asli? Jika siswa menggunakan AI untuk mengecek tata bahasa, apakah itu curang? Plagiarisme 2.0 memerlukan definisi baru yang lebih bernuansa: bukan hitam-putih, tetapi tergantung pada tingkat keterlibatan siswa, transparansi, dan tujuan penggunaan AI.</p>
        <p>Prinsip baru untuk plagiarisme 2.0: (1) transparansi adalah kunci: siswa harus jujur tentang bagaimana mereka menggunakan AI; (2) keterlibatan manusia tetap esensial: siswa harus menambahkan suara pribadi, ide orisinal, atau pengalaman unik; (3) konteks menentukan: penggunaan AI untuk tugas refleksi pribadi berbeda dengan tugas faktual; (4) tujuan pembelajaran menentukan: jika tujuan adalah belajar menulis mandiri, menggunakan AI untuk menulis seluruh tugas adalah menyontek; jika tujuan adalah belajar menggunakan AI, maka itu sah.</p>
        <p>Contoh definisi baru penyontekan di era AI: "Menyontek": Menggunakan AI untuk menulis seluruh tugas tanpa transparansi, tanpa revisi, dan tanpa keterlibatan pikiran sendiri. – "Karya Asli": Tulisan yang ide utamanya dari siswa, AI hanya sebagai alat bantu (brainstorming, rangkuman, koreksi), dan siswa mencantumkan penggunaan AI secara transparan. – "Gray Area": Menggunakan AI untuk parafrase sebagian tugas. Ini sah jika siswa tetap mengkritik, merevisi, dan menambahkan suara pribadi. – "Etis": "Saya menggunakan AI untuk [tujuan], lalu saya revisi dengan [apa yang saya tambahkan]. Ide utama tetap dari saya." Dengan mendefinisikan ulang plagiarisme 2.0, guru dan siswa dapat berdiskusi lebih terbuka tentang etika AI tanpa hitam-putih yang kaku.</p>
    </div>
</div>
