<!-- 9-6: Menggeser Paradigma: Mengintegrasikan AI ke Dalam "Proses" Penilaian, Bukan Sekadar "Hasil Akhir" -->
<div class="mb-20">
    <img src="https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&q=80&w=1200" alt="Penilaian proses" class="w-full h-[400px] md:h-[500px] object-cover rounded-3xl shadow-xl mb-8">
    <h2 class="text-3xl md:text-4xl font-extrabold text-slate-800 mb-6"><i class="fas fa-sync-alt mr-3 text-yellow-500"></i>9-6. Menggeser Paradigma: Mengintegrasikan AI ke Dalam "Proses" Penilaian, Bukan Sekadar "Hasil Akhir"</h2>
    <div class="prose prose-lg prose-slate max-w-none text-slate-600 leading-relaxed">
        <p>Paradigma penilaian tradisional fokus pada hasil akhir: tugas yang dikumpulkan, nilai ujian, atau produk final. Paradigma ini mudah dibobol oleh AI karena siswa dapat menghasilkan produk akhir tanpa proses belajar yang nyata. Menggeser paradigma ke penilaian proses berarti guru menilai bagaimana siswa belajar, berpikir, dan berkembang, bukan hanya apa yang mereka hasilkan. AI dapat diintegrasikan ke dalam proses penilaian sebagai alat bantu yang dipantau, bukan sebagai musuh yang harus dicegah.</p>
        <p>Contoh integrasi AI ke dalam penilaian proses: (1) minta siswa menyerahkan draft berulang dengan catatan revisi; (2) minta siswa merekam sesi brainstorming dengan AI dan jelaskan bagaimana mereka menggunakan saran AI; (3) nilai bagaimana siswa mengkritik dan memperbaiki output AI, bukan hanya output itu sendiri; (4) gunakan penilaian berbasis portofolio yang menunjukkan perkembangan dari waktu ke waktu. Dengan penilaian proses, guru dapat melihat apakah siswa benar-benar belajar, bahkan jika mereka menggunakan AI sebagai alat bantu.</p>
        <p>Contoh kriteria penilaian proses yang mengintegrasikan AI: "Draft 1: Ide awal kamu sebelum pakai AI." – "Draft 2: Setelah pakai AI untuk brainstorming, apa yang kamu tambah/kurangi?" – "Draft 3: Setelah revisi mandiri, bagaimana kamu memperbaiki kelemahan draft 2?" – "Refleksi: Jelaskan bagaimana AI membantumu, apa yang kamu pelajari dari interaksi dengan AI, dan apa yang akan kamu lakukan berbeda next time." Dengan menggeser paradigma ke penilaian proses, guru menilai perkembangan belajar siswa secara holistik dan mengurangi dorongan untuk menyontek via AI.</p>
    </div>
</div>