<!-- 10-10: Puncak Transformasi: Melepaskan Ego Lama dan Mentransformasi Diri Menjadi Arsitek Pembelajaran -->
<div class="mb-20">
    <img src="https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&q=80&w=1200" alt="Guru transformasi" class="w-full h-[400px] md:h-[500px] object-cover rounded-3xl shadow-xl mb-8">
    <h2 class="text-3xl md:text-4xl font-extrabold text-slate-800 mb-6"><i class="fas fa-chalkboard-user mr-3 text-teal-500"></i>10-10. Puncak Transformasi: Melepaskan Ego Lama dan Mentransformasi Diri Menjadi Arsitek Pembelajaran</h2>
    <div class="prose prose-lg prose-slate max-w-none text-slate-600 leading-relaxed">
        <p>Transformasi guru di era AI bukan hanya tentang mengadopsi tools baru, tetapi tentang melepaskan ego lama dan mengadopsi identitas baru. Ego lama: guru sebagai sumber pengetahuan tunggal, guru yang takut digantikan AI, guru yang menolak perubahan. Identitas baru: guru sebagai arsitek pembelajaran yang mendesain pengalaman belajar bermakna, fasilitator yang membimbing siswa berpikir kritis, dan mitra yang berkolaborasi dengan AI untuk memperkuat pembelajaran. Melepaskan ego lama memerlukan kerendahan hati, keberanian, dan kepercayaan bahwa nilai guru tetap tak tergantikan oleh AI.</p>
        <p>Peran guru sebagai arsitek pembelajaran: (1) mendesain pengalaman belajar yang mengaktifkan siswa, bukan hanya menyampaikan materi; (2) memfasilitasi diskusi, refleksi, dan proyek yang memerlukan kecerdasan emosional dan kreativitas; (3) menggunakan AI untuk mengotomatisasi tugas administratif dan memberikan feedback instan, sehingga guru fokus pada interaksi manusiawi; (4) membimbing siswa menjadi pengguna AI yang kritis dan beretika; (5) terus belajar sepanjang hayat dan menjadi model bagi siswa. Guru yang bertransformasi menjadi arsitek pembelajaran akan lebih relevan, bermakna, dan terpenuhi dalam profesinya.</p>
        <p>Contoh pergeseran mindset dari ego lama ke identitas baru: Ego Lama: "Saya takut AI menggantikan saya." → Identitas Baru: "AI adalah alat yang memperkuat kemampuan saya mengajar." Ego Lama: "Saya harus tahu semua jawaban." → Identitas Baru: "Saya mengajarkan siswa cara mencari dan mengevaluasi jawaban." Ego Lama: "Tugas saya adalah menyampaikan materi." → Identitas Baru: "Tugas saya adalah mendesain pengalaman belajar yang mengaktifkan siswa." Ego Lama: "Perubahan mengancam." → Identitas Baru: "Perubahan adalah peluang untuk berkembang." Ego Lama: "Saya sendirian dalam perubahan ini." → Identitas Baru: "Saya membangun komunitas untuk belajar bersama." Dengan melepaskan ego lama dan mengadopsi identitas arsitek pembelajaran, guru tidak hanya bertahan di era AI, tetapi berkembang menjadi pendidik yang lebih bermakna, relevan, dan terpenuhi.</p>
    </div>
</div>