<!-- 10-4: Membuat Asisten Chatbot Sederhana Berbasis WhatsApp untuk Tanya Jawab Materi Murid 24/7 -->
<div class="mb-20">
    <img src="https://images.unsplash.com/photo-1611746745350-8969f4e99c1c?auto=format&fit=crop&q=80&w=1200" alt="Chatbot WhatsApp" class="w-full h-[400px] md:h-[500px] object-cover rounded-3xl shadow-xl mb-8">
    <h2 class="text-3xl md:text-4xl font-extrabold text-slate-800 mb-6"><i class="fab fa-whatsapp mr-3 text-green-600"></i>10-4. Membuat Asisten Chatbot Sederhana Berbasis WhatsApp untuk Tanya Jawab Materi Murid 24/7</h2>
    <div class="prose prose-lg prose-slate max-w-none text-slate-600 leading-relaxed">
        <p>Siswa sering memiliki pertanyaan di luar jam sekolah: malam hari, akhir pekan, atau saat belajar mandiri. Chatbot WhatsApp dapat menjadi asisten 24/7 yang menjawab pertanyaan dasar tentang materi, mengingatkan tugas, atau memberikan sumber belajar. Chatbot tidak menggantikan guru, tetapi memperluas jangkauan dukungan belajar siswa. Dengan chatbot, siswa tidak perlu menunggu besok untuk bertanya, dan guru tidak terus-menerus diganggu pesan di luar jam kerja.</p>
        <p>Cara membuat chatbot WhatsApp sederhana: (1) gunakan platform no-code seperti Wati, Chatfuel, atau Respond.io; (2) buat alur percakapan berbasis aturan (if-then): jika siswa tanya "tugas matematika", kirim link tugas; jika siswa tanya "materi bab 3", kirim PDF ringkasan; (3) untuk pertanyaan yang lebih kompleks, chatbot dapat mengarahkan ke guru atau konselor; (4) integrasikan dengan Google Drive atau LMS untuk akses materi otomatis. Guru dapat memulai dengan chatbot sederhana, lalu meningkatkan ke AI-powered chatbot seiring waktu.</p>
        <p>Contoh alur chatbot WhatsApp: Siswa: "Halo, apa tugas matematika minggu ini?" Chatbot: "Tugas matematika minggu ini: latihan bab 5 nomor 1–20, kumpulkan Jumat. Link PDF latihan: [link]. Ada yang lain yang bisa dibantu?" Siswa: "Saya tidak paham materi bab 3." Chatbot: "Materi bab 3: [ringkasan singkat]. Video penjelasan: [link YouTube]. Ringkasan PDF: [link Drive]. Kalau masih bingung, coba tanya guru di jam konsultasi atau sambung ke konselor." Dengan chatbot WhatsApp, siswa mendapat dukungan belajar 24/7, dan guru memiliki batas sehat antara pekerjaan dan kehidupan pribadi.</p>
    </div>
</div>
