<!-- 10-7: Workflow Pembuatan E-Sertifikat Apresiasi Siswa Berprestasi Secara Massal dan Cepat -->
<div class="mb-20">
    <img src="https://images.unsplash.com/photo-1606326608606-aa0b62935f2b?auto=format&fit=crop&q=80&w=1200" alt="E-sertifikat" class="w-full h-[400px] md:h-[500px] object-cover rounded-3xl shadow-xl mb-8">
    <h2 class="text-3xl md:text-4xl font-extrabold text-slate-800 mb-6"><i class="fas fa-certificate mr-3 text-yellow-500"></i>10-7. Workflow Pembuatan E-Sertifikat Apresiasi Siswa Berprestasi Secara Massal dan Cepat</h2>
    <div class="prose prose-lg prose-slate max-w-none text-slate-600 leading-relaxed">
        <p>Memberikan apresiasi kepada siswa berprestasi penting untuk motivasi, tetapi membuat sertifikat manual untuk puluhan siswa memakan waktu. Workflow otomatisasi E-sertifikat memungkinkan guru menghasilkan ratusan sertifikat dalam hitungan menit. Setiap sertifikat personalized dengan nama siswa, prestasi, tanggal, dan tanda tangan guru. E-sertifikat dapat dikirim via email atau WhatsApp, atau dipajang di website sekolah. Otomatisasi ini menunjukkan penghargaan yang tulus dan konsisten kepada semua siswa berprestasi.</p>
        <p>Workflow pembuatan E-sertifikat massal: (1) siapkan template sertifikat di Google Docs atau Canva dengan placeholder <code>@{{nama}}</code>, <code>@{{prestasi}}</code>, <code>@{{tanggal}}</code>; (2) siapkan spreadsheet dengan data siswa (nama, prestasi, tanggal); (3) gunakan tools otomatisasi seperti Google Apps Script, Canva API, atau Zapier + PDF Generator untuk generate sertifikat per siswa; (4) simpan sebagai PDF dengan nama file otomatis (misalnya "Sertifikat_Budi_PrestasiMatematika_2026.pdf"); (5) kirim otomatis via email atau WhatsApp.</p>
        <p>Contoh workflow E-sertifikat otomatis: Spreadsheet Kolom: Nama, Kelas, Prestasi, Tanggal, Email Orang Tua. Template Canva: "Sertifikat Apresiasi. Ini diberikan kepada [Nama] kelas [Kelas] atas prestasi [Prestasi] pada [Tanggal]. Tanda tangan Guru." Otomatisasi: "Setiap kali tombol 'Generate Sertifikat' ditekan, buat 1 PDF per siswa, simpan di Google Drive, dan kirim email ke orang tua dengan sertifikat sebagai attachment." Hasil: 50 sertifikat selesai dalam 10 menit, bukan 5 jam manual. Dengan workflow otomatisasi E-sertifikat, guru dapat memberikan apresiasi secara massal, konsisten, dan cepat kepada semua siswa berprestasi.</p>
    </div>
</div>