<!-- 10-1: Pengenalan No-Code Tools Dasar untuk Otomatisasi Pekerjaan Guru (Contoh: Zapier, Make.com) -->
<div class="mb-20">
    <img src="https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=1200" alt="No-code automation" class="w-full h-[400px] md:h-[500px] object-cover rounded-3xl shadow-xl mb-8">
    <h2 class="text-3xl md:text-4xl font-extrabold text-slate-800 mb-6"><i class="fas fa-robot mr-3 text-blue-500"></i>10-1. Pengenalan No-Code Tools Dasar untuk Otomatisasi Pekerjaan Guru (Contoh: Zapier, Make.com)</h2>
    <div class="prose prose-lg prose-slate max-w-none text-slate-600 leading-relaxed">
        <p>No-code tools adalah aplikasi yang memungkinkan pengguna membuat otomatisasi tanpa perlu coding. Bagi guru, no-code tools seperti Zapier dan Make.com dapat menghemat waktu dengan mengotomatisasi tugas repetitif seperti mengirim email otomatis, rekap data, atau notifikasi. Dengan no-code, guru tidak perlu belajar coding rumit; cukup gunakan antarmuka drag-and-drop untuk menghubungkan aplikasi satu sama lain. Otomatisasi ini memungkinkan guru fokus pada pekerjaan yang lebih bernilai: mengajar, membimbing siswa, dan berinteraksi secara manusiawi.</p>
        <p>Zapier adalah platform no-code yang menghubungkan ribuan aplikasi (Google Sheets, Gmail, WhatsApp, Slack, dll). Contoh otomatisasi sederhana: "Setiap kali ada siswa mengisi Google Forms, kirim email konfirmasi otomatis ke siswa dan catat jawabannya di Google Sheets." Make.com (sebelumnya Integromat) lebih fleksibel untuk workflow kompleks dengan logika kondisional. Guru dapat memulai dengan otomatisasi sederhana, lalu berkembang ke workflow yang lebih canggih seiring pemahaman meningkat.</p>
        <p>Contoh otomatisasi no-code untuk guru: "Setiap kali nilai baru masuk ke Google Sheets, kirim email notifikasi ke orang tua secara otomatis." – "Setiap Jumat sore, kirim reminder otomatis ke siswa tentang tugas yang belum dikumpulkan." – "Ketika siswa absen 3x berturut-turut, kirim peringatan otomatis ke konselor dan orang tua." – "Setiap kali ada tugas baru di Google Classroom, posting pengumuman otomatis ke grup WhatsApp kelas." Dengan no-code tools, guru menghemat waktu berjam-jam setiap minggu dan mengurangi beban administratif yang melelahkan.</p>
    </div>
</div>