<!-- 10-2: Integrasi Google Forms dengan AI untuk Analisis Sentimen dan Umpan Balik Siswa Secara Real-time -->
<div class="mb-20">
    <img src="https://images.unsplash.com/photo-1526628953301-3e589a6a8b74?auto=format&fit=crop&q=80&w=1200" alt="Analisis sentimen" class="w-full h-[400px] md:h-[500px] object-cover rounded-3xl shadow-xl mb-8">
    <h2 class="text-3xl md:text-4xl font-extrabold text-slate-800 mb-6"><i class="fas fa-chart-line mr-3 text-green-500"></i>10-2. Integrasi Google Forms dengan AI untuk Analisis Sentimen dan Umpan Balik Siswa Secara Real-time</h2>
    <div class="prose prose-lg prose-slate max-w-none text-slate-600 leading-relaxed">
        <p>Google Forms adalah alat sederhana untuk mengumpulkan umpan balik siswa, tetapi analisis manual memakan waktu. Dengan integrasi AI, guru dapat menganalisis sentimen siswa secara real-time: apakah siswa merasa senang, frustrasi, bosan, atau termotivasi setelah pembelajaran. Analisis sentimen membantu guru mendeteksi masalah lebih dini, menyesuaikan strategi mengajar, dan merespon kebutuhan siswa secara proaktif. Integrasi ini juga menunjukkan kepada siswa bahwa perasaan mereka didengar dan dihargai.</p>
        <p>Cara integrasi Google Forms dengan AI: (1) buat Google Forms dengan pertanyaan terbuka seperti "Bagaimana perasaanmu setelah pelajaran hari ini?" atau "Apa yang membuatmu sulit paham hari ini?"; (2) sambungkan Google Forms ke Google Sheets; (3) gunakan AI untuk menganalisis setiap jawaban baru dan kategorikan sentimen (positif, netral, negatif); (4) buat dashboard sederhana yang menampilkan tren sentimen dari waktu ke waktu. AI juga dapat merangkum tema utama dari umpan balik siswa, seperti "banyak siswa merasa terlalu cepat" atau "siswa ingin lebih banyak contoh praktis".</p>
        <p>Contoh pertanyaan Google Forms untuk analisis sentimen: "Skala 1–5, seberapa nyaman kamu dengan kecepatan pelajaran hari ini?" – "Apa satu hal yang paling kamu suka dari pelajaran hari ini?" – "Apa satu hal yang membuatmu frustrasi atau bingung hari ini?" – "Apakah kamu merasa didukung oleh guru hari ini? Jelaskan mengapa." – "Saranku untuk meningkatkan pelajaran berikutnya: ____" Dengan integrasi Google Forms dan AI, guru mendapatkan wawasan real-time tentang pengalaman siswa dan dapat menyesuaikan pembelajaran secara responsif.</p>
    </div>
</div>