<!-- 10-5: Melatih Custom GPT (OpenAI) Menggunakan Dokumen Kurikulum Spesifik Milik Sekolah Anda Sendiri -->
<div class="mb-20">
    <img src="https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&q=80&w=1200" alt="Custom GPT" class="w-full h-[400px] md:h-[500px] object-cover rounded-3xl shadow-xl mb-8">
    <h2 class="text-3xl md:text-4xl font-extrabold text-slate-800 mb-6"><i class="fas fa-brain mr-3 text-purple-500"></i>10-5. Melatih Custom GPT (OpenAI) Menggunakan Dokumen Kurikulum Spesifik Milik Sekolah Anda Sendiri</h2>
    <div class="prose prose-lg prose-slate max-w-none text-slate-600 leading-relaxed">
        <p>Custom GPT (OpenAI) adalah versi AI yang dilatih dengan data spesifik milik pengguna. Sekolah dapat melatih Custom GPT dengan dokumen kurikulum, silabus, materi ajar, atau pedoman sekolah sendiri. Custom GPT ini akan menjawab pertanyaan berdasarkan konteks sekolah, bukan hanya pengetahuan umum AI. Ini memastikan informasi yang diberikan akurat, relevan, dan konsisten dengan standar sekolah. Custom GPT juga menjadi database pengetahuan yang dapat diakses guru dan siswa kapan saja.</p>
        <p>Cara melatih Custom GPT: (1) kumpulkan dokumen relevan (kurikulum, silabus, RPP, pedoman, materi ajar) dalam format PDF/DOCX; (2) upload ke platform Custom GPT di OpenAI; (3) instruksikan AI: "Jawab hanya berdasarkan dokumen yang saya berikan. Jika tidak ada di dokumen, katakan 'Saya tidak tahu'."; (4) test dengan pertanyaan umum dari guru/siswa; (5) sesuaikan instruksi jika ada kesalahan. Custom GPT dapat diakses via web atau diintegrasikan ke website sekolah.</p>
        <p>Contoh pertanyaan yang dijawab Custom GPT berbasis kurikulum sekolah: Siswa: "Apa kompetensi dasar untuk bab 3 Matematika kelas 8?" Custom GPT: "Berdasarkan kurikulum sekolah kami, kompetensi dasar bab 3 Matematika kelas 8: (1) Memahami hubungan antar sudut, (2) Menghitung luas segitiga dan segi empat, (3) Menerapkan teorema Pythagoras." Guru: "Apa prosedur jika siswa sakit di kelas?" Custom GPT: "Berdasarkan pedoman sekolah: (1) Tenangkan siswa, (2) Hubungi UKS, (3) Hubungi orang tua, (4) Dokumentasikan di buku incident report." Dengan Custom GPT berbasis kurikulum sendiri, sekolah memiliki asisten cerdas yang konsisten, akurat, dan mendukung pembelajaran.</p>
    </div>
</div>