<!-- 10-3: Menyambungkan Spreadsheet (Data Nilai Rapor) dengan Generator Dokumen PDF Otomatis -->
<div class="mb-20">
    <img src="https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&q=80&w=1200" alt="Rapor otomatis" class="w-full h-[400px] md:h-[500px] object-cover rounded-3xl shadow-xl mb-8">
    <h2 class="text-3xl md:text-4xl font-extrabold text-slate-800 mb-6"><i class="fas fa-file-pdf mr-3 text-red-500"></i>10-3. Menyambungkan Spreadsheet (Data Nilai Rapor) dengan Generator Dokumen PDF Otomatis</h2>
    <div class="prose prose-lg prose-slate max-w-none text-slate-600 leading-relaxed">
        <p>Membuat rapor manual adalah tugas administratif yang memakan waktu dan rentan kesalahan. Dengan menyambungkan spreadsheet (Google Sheets atau Excel) dengan generator dokumen PDF otomatis, guru dapat menghasilkan ratusan rapor dalam hitungan menit. Setiap baris spreadsheet merepresentasikan satu siswa dengan data nilai, nama, narasi, dan informasi lainnya. Generator PDF otomatis mengisi template rapor dengan data dari spreadsheet, menghasilkan PDF individual untuk setiap siswa yang siap dikirim ke orang tua.</p>
        <p>Alat yang dapat digunakan: Google Apps Script (gratis, terintegrasi dengan Google Sheets), DocuGenerators, atau tools no-code seperti Zapier + PDF Generator. Workflow sederhana: (1) siapkan template rapor di Google Docs dengan placeholder seperti <code>@{{nama}}</code>, <code>@{{nilai_matematika}}</code>, <code>@{{narasi}}</code>; (2) isi spreadsheet dengan data siswa; (3) jalankan script/otomatisasi untuk generate PDF untuk setiap siswa; (4) simpan PDF di Google Drive dengan nama file otomatis (misalnya "Rapor_NamaSiswa_Kelas8A.pdf"). Guru hanya perlu review final sebelum kirim.</p>
        <p>Contoh workflow otomatisasi rapor: Spreadsheet Kolom: Nama, Kelas, Nilai Matematika, Nilai IPS, Nilai Bahasa, Narasi Matematika, Narasi IPS, Narasi Bahasa, Tanda Tangan Guru. Template Google Docs: "Rapor Semester Genap [Tahun] [Nama] kelas [Kelas]. Nilai Matematika: [Nilai]. Narasi: [Narasi]." Otomatisasi: "Setiap kali tombol 'Generate Rapor' ditekan di Sheets, buat 1 PDF per siswa, simpan di folder 'Rapor 2026', dan kirim email ke orang tua." Hasil: 30 rapor selesai dalam 5 menit, bukan 5 jam manual. Dengan otomatisasi rapor, guru menghemat waktu, mengurangi kesalahan input, dan fokus pada hal yang lebih penting: membimbing siswa.</p>
    </div>
</div>