<!-- 10-9: Strategi Membangun Komunitas Praktisi AI di Ruang Guru (Cara Menjadi Inisiator Diseminasi) -->
<div class="mb-20">
    <img src="https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&q=80&w=1200" alt="Komunitas guru AI" class="w-full h-[400px] md:h-[500px] object-cover rounded-3xl shadow-xl mb-8">
    <h2 class="text-3xl md:text-4xl font-extrabold text-slate-800 mb-6"><i class="fas fa-users mr-3 text-orange-500"></i>10-9. Strategi Membangun Komunitas Praktisi AI di Ruang Guru (Cara Menjadi Inisiator Diseminasi)</h2>
    <div class="prose prose-lg prose-slate max-w-none text-slate-600 leading-relaxed">
        <p>Komunitas praktisi AI di ruang guru adalah wadah bagi guru untuk berbagi pengalaman, belajar bersama, dan berkolaborasi dalam menggunakan AI untuk pembelajaran. Komunitas ini penting untuk mempercepat adopsi teknologi, mengurangi isolasi guru yang ingin belajar AI, dan menciptakan budaya inovasi di sekolah. Sebagai inisiator, guru dapat memulai komunitas kecil, mengundang rekan yang tertarik, dan secara bertahap memperluas ke seluruh sekolah. Komunitas yang kuat akan mendorong transformasi digital secara organik dan berkelanjutan.</p>
        <p>Strategi membangun komunitas praktisi AI: (1) identifikasi 3–5 guru yang tertarik dengan AI sebagai founding members; (2) buat grup WhatsApp/Slack untuk komunikasi rutin; (3) jadwalkan pertemuan bulanan (30–60 menit) untuk berbagi tools, tips, dan tantangan; (4) undang narasumber eksternal (praktisi AI, guru dari sekolah lain) secara berkala; (5) dokumentasikan pembelajaran dalam shared drive atau blog internal; (6) rayakan keberhasilan kecil untuk mempertahankan momentum. Komunitas tidak perlu formal; yang penting adalah konsistensi dan rasa saling mendukung.</p>
        <p>Contoh agenda pertemuan komunitas praktisi AI: Pertemuan 1: "Perkenalan: Apa AI yang sudah kamu coba? Apa tantanganmu?" Pertemuan 2: "Workshop: Cara menggunakan ChatGPT untuk membuat soal latihan." Pertemuan 3: "Share session: Budi berbagi cara membuat chatbot WhatsApp untuk kelasnya." Pertemuan 4: "Diskusi: Bagaimana mengatasi resistensi dari guru yang skeptis terhadap AI?" Pertemuan 5: "Guest speaker: Praktisi AI dari luar sekolah berbagi tren terbaru." Pertemuan 6: "Review progres: Apa yang sudah berhasil? Apa yang masih sulit? Rencana next month." Dengan komunitas praktisi AI, guru tidak belajar sendirian, tetapi berkembang bersama dalam lingkungan yang suportif dan inspiratif.</p>
    </div>
</div>