<!-- 10-6: Otomatisasi Rekap Kehadiran Siswa Menggunakan Teknologi Image Recognition Dasar -->
<div class="mb-20">
    <img src="https://images.unsplash.com/photo-1581091226033-d5c48150dbaa?auto=format&fit=crop&q=80&w=1200" alt="Face recognition" class="w-full h-[400px] md:h-[500px] object-cover rounded-3xl shadow-xl mb-8">
    <h2 class="text-3xl md:text-4xl font-extrabold text-slate-800 mb-6"><i class="fas fa-camera mr-3 text-indigo-500"></i>10-6. Otomatisasi Rekap Kehadiran Siswa Menggunakan Teknologi Image Recognition Dasar</h2>
    <div class="prose prose-lg prose-slate max-w-none text-slate-600 leading-relaxed">
        <p>Rekap kehadiran manual memakan waktu dan rentan kesalahan. Teknologi image recognition (pengenalan gambar) dapat mengotomatisasi proses ini: siswa foto wajah atau scan QR code saat masuk kelas, sistem otomatis mencatat kehadiran. Image recognition berbasis wajah lebih canggih dan sulit dipalsukan, tetapi memerlukan privasi dan keamanan data. QR code lebih sederhana dan mudah diimplementasikan. Otomatisasi kehadiran menghemat waktu guru 5–10 menit setiap hari dan menghasilkan data akurat untuk analisis.</p>
        <p>Cara implementasi rekap kehadiran otomatis: (1) pasang kamera atau tablet di pintu kelas; (2) siswa scan QR code personal atau foto wajah saat masuk; (3) sistem menggunakan image recognition untuk memverifikasi identitas; (4) data kehadiran langsung masuk ke Google Sheets atau database sekolah; (5) guru dapat melihat rekap real-time di dashboard. Untuk privasi, pastikan data wajah dienkripsi, hanya diakses personel berwenang, dan orang tua memberikan izin.</p>
        <p>Contoh workflow rekap kehadiran otomatis: Langkah 1: Siswa datang, scan QR code pribadi di tablet di pintu kelas. Langkah 2: Sistem memverifikasi QR code, cocokkan dengan database siswa. Langkah 3: Sistem catat: "Nama: Budi, Kelas: 8A, Waktu: 07:05, Status: Hadir". Langkah 4: Data langsung masuk ke Google Sheets rekap kehadiran. Langkah 5: Guru membuka dashboard, lihat siapa yang hadir/tidak tanpa rolls manual. Notifikasi otomatis: Jika siswa absen 3x berturut-turut, kirim email/peringatan ke orang tua. Dengan otomatisasi kehadiran, guru menghemat waktu, data akurat, dan dapat fokus pada interaksi dengan siswa yang hadir.</p>
    </div>
</div>