<!-- 10-8: Membangun Database Pengetahuan Sekolah (Knowledge Base) Internal Berbasis AI -->
<div class="mb-20">
    <img src="https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=1200" alt="Knowledge base" class="w-full h-[400px] md:h-[500px] object-cover rounded-3xl shadow-xl mb-8">
    <h2 class="text-3xl md:text-4xl font-extrabold text-slate-800 mb-6"><i class="fas fa-database mr-3 text-cyan-500"></i>10-8. Membangun Database Pengetahuan Sekolah (Knowledge Base) Internal Berbasis AI</h2>
    <div class="prose prose-lg prose-slate max-w-none text-slate-600 leading-relaxed">
        <p>Database pengetahuan (knowledge base) internal adalah repositori terpusat berisi semua informasi penting sekolah: SOP, pedoman, kurikulum, FAQ, materi pelatihan, dan dokumen relevan. Knowledge base berbasis AI memungkinkan guru dan staf mencari informasi secara cepat dengan bertanya dalam bahasa alami, bukan browsing folder bingung. AI akan mencari di seluruh database, memberikan jawaban ringkas, dan menyertakan sumber referensi. Knowledge base ini mengurangi waktu mencari informasi, meningkatkan konsistensi informasi, dan memudahkan onboarding guru baru.</p>
        <p>Cara membangun knowledge base berbasis AI: (1) kumpulkan semua dokumen relevan (PDF, DOCX, spreadsheet) dalam satu tempat (Google Drive, SharePoint); (2) gunakan platform AI seperti Notion AI, Guru, atau custom GPT untuk index semua dokumen; (3) instruksikan AI: "Jawab pertanyaan berdasarkan dokumen di knowledge base. Sertakan link sumber."; (4) test dengan pertanyaan umum dari guru/staf; (5) update knowledge base secara berkala saat ada perubahan kebijakan atau dokumen baru.</p>
        <p>Contoh pertanyaan yang dijawab knowledge base AI: Guru Baru: "Bagaimana prosedur mengajukan cuti?" AI: "Prosedur cuti: (1) Isi form cuti di portal HR, (2) Kirim ke kepala sekolah untuk persetujuan, (3) CC ke HRD. Form: [link]. Template: [link]." Guru: "Apa SOP jika siswa berkelahi di kelas?" AI: "SOP konflik siswa: (1) Pisahkan siswa, (2) Tenangkan kedua pihak, (3) Hubungi konselor, (4) Dokumentasikan di incident report, (5) Hubungi orang tua. Form incident report: [link]." Dengan knowledge base berbasis AI, sekolah memiliki sistem pengetahuan terpusat yang efisien, konsisten, dan mudah diakses oleh semua pemangku kepentingan.</p>
    </div>
</div>