<!-- 8-10: Mengubah Format Laporan PTK Menjadi Artikel Jurnal Ringkas yang Siap Publikasi -->
<div class="mb-20">
    <img src="https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&q=80&w=1200" alt="Publikasi jurnal" class="w-full h-[400px] md:h-[500px] object-cover rounded-3xl shadow-xl mb-8">
    <h2 class="text-3xl md:text-4xl font-extrabold text-slate-800 mb-6"><i class="fas fa-file-alt mr-3 text-cyan-500"></i>8-10. Mengubah Format Laporan PTK Menjadi Artikel Jurnal Ringkas yang Siap Publikasi</h2>
    <div class="prose prose-lg prose-slate max-w-none text-slate-600 leading-relaxed">
        <p>Mengubah laporan PTK yang panjang menjadi artikel jurnal ringkas adalah keterampilan penting untuk diseminasi hasil penelitian. Artikel jurnal memiliki struktur berbeda dari laporan PTK: lebih ringkas, fokus pada kontribusi baru, dan mengikuti format standar jurnal (abstrak, pendahuluan, metode, hasil, pembahasan, kesimpulan, referensi). Guru perlu menyaring konten laporan PTK, mempertahankan bagian yang paling relevan, dan menulis ulang dengan gaya bahasa jurnal yang lebih padat dan akademis. Artikel jurnal yang baik memiliki 3000–5000 kata, tergantung target jurnal.</p>
        <p>Langkah mengubah PTK menjadi artikel jurnal: (1) pilih jurnal target dan baca panduan penulisnya; (2) tulis ulang abstrak 150–250 kata yang mencakup tujuan, metode, hasil, dan implikasi; (3) ringkas pendahuluan menjadi 1–2 halaman yang menonjolkan gap penelitian dan kontribusi; (4) sederhanakan metode, fokus pada desain, subjek, dan intervensi; (5) presentasikan hasil dengan tabel/grafik kunci; (6) pembahasan mengaitkan temuan dengan literatur; (7) kesimpulan dan saran ringkas; (8) sesuaikan format referensi sesuai jurnal target.</p>
        <p>Contoh struktur artikel jurnal dari PTK: Abstrak: "Penelitian ini bertujuan menguji efektivitas metode diskusi kelompok terhadap keaktifan siswa Kelas VIII-A SMP. Menggunakan desain PTK 2 siklus, hasil menunjukkan keaktifan meningkat dari 30% menjadi 85%. Temuan ini mendukung penerapan diskusi kelompok sebagai strategi pembelajaran kolaboratif." Pendahuluan (1–2 halaman): Konteks, masalah, gap penelitian, tujuan, kontribusi. Metode (1 halaman): Desain PTK, subjek 30 siswa, instrumen observasi dan kuesioner, 2 siklus. Hasil (1–2 halaman): Tabel perbandingan Siklus 1–2, grafik tren keaktifan, statistik deskriptif. Pembahasan (1–2 halaman): Interpretasi temuan, kaitkan dengan literatur Smith (2023) dan Lee (2022). Kesimpulan & Saran (0.5 halaman): Ringkasan temuan, saran untuk guru dan peneliti. Referensi: 15–20 sumber relevan, format APA edisi ke-7. Dengan mengubah PTK menjadi artikel jurnal yang ringkas dan terstruktur, guru dapat mendiseminasikan hasil penelitian ke komunitas akademik yang lebih luas.</p>
    </div>
</div>