<!-- 8-4: Menyusun Kerangka Metodologi Penelitian Secara Sistematis (Siklus 1, Siklus 2, dst) -->
<div class="mb-20">
    <img src="https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=1200" alt="Metodologi PTK" class="w-full h-[400px] md:h-[500px] object-cover rounded-3xl shadow-xl mb-8">
    <h2 class="text-3xl md:text-4xl font-extrabold text-slate-800 mb-6"><i class="fas fa-chalkboard-teacher mr-3 text-purple-500"></i>8-4. Menyusun Kerangka Metodologi Penelitian Secara Sistematis (Siklus 1, Siklus 2, dst)</h2>
    <div class="prose prose-lg prose-slate max-w-none text-slate-600 leading-relaxed">
        <p>Metodologi PTK yang sistematis mengikuti pola siklus: perencanaan, tindakan, observasi, dan refleksi, yang diulang hingga target tercapai. Kerangka metodologi yang jelas memudahkan guru menjalankan penelitian tanpa kebingungan, sekaligus memudahkan reviewer memahami alur penelitian. Setiap siklus harus memiliki tujuan spesifik, tindakan yang terukur, instrumen observasi yang sesuai, dan kriteria keberhasilan yang jelas. Menyusun kerangka metodologi secara sistematis juga memastikan bahwa PTK Anda dapat direplikasi oleh guru lain di konteks serupa.</p>
        <p>Dalam menyusun kerangka, mulai dengan mendeskripsikan konteks penelitian (lokasi, subjek, mata pelajaran), lalu uraikan setiap siklus secara rinci: (1) perencanaan: apa yang direncanakan dan mengapa; (2) tindakan: langkah konkret yang dilakukan; (3) observasi: data apa yang dikumpulkan dan bagaimana; (4) refleksi: apa yang dipelajari dan bagaimana rencana disesuaikan untuk siklus berikutnya. Pastikan ada indikator keberhasilan yang terukur untuk setiap siklus, misalnya peningkatan nilai rata-rata 20% atau peningkatan keaktifan dari 30% menjadi 70%.</p>
        <p>Contoh kerangka metodologi siklus: Siklus 1 – Perencanaan: Menyusun RPP dengan metode diskusi kelompok, menyiapkan lembar observasi keaktifan. Tindakan: Melaksanakan diskusi kelompok 4 kali pertemuan. Observasi: Mengamati keaktifan siswa menggunakan lembar observasi, mencatat frekuensi kontribusi. Refleksi: Keaktifan meningkat dari 30% menjadi 50%, tetapi beberapa siswa masih pasif. Rencana revisi: berikan peran spesifik dalam kelompok. Siklus 2 – Perencanaan: Revisi RPP dengan penugasan peran jelas (ketua, notulen, presenter). Tindakan: Melaksanakan diskusi kelompok 4 pertemuan dengan peran terstruktur. Observasi & Refleksi: Sama seperti Siklus 1, target keaktifan 75%. Dengan kerangka metodologi yang sistematis, PTK berjalan terstruktur dan hasilnya dapat dipertanggungjawabkan.</p>
    </div>
</div>