<!-- 8-7: Menggunakan AI sebagai Proofreader Tangguh dan Editor Tata Bahasa Akademik Baku -->
<div class="mb-20">
    <img src="https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&q=80&w=1200" alt="Proofreading AI" class="w-full h-[400px] md:h-[500px] object-cover rounded-3xl shadow-xl mb-8">
    <h2 class="text-3xl md:text-4xl font-extrabold text-slate-800 mb-6"><i class="fas fa-spell-check mr-3 text-teal-500"></i>8-7. Menggunakan AI sebagai Proofreader Tangguh dan Editor Tata Bahasa Akademik Baku</h2>
    <div class="prose prose-lg prose-slate max-w-none text-slate-600 leading-relaxed">
        <p>Proofreading dan editing adalah tahap krusial sebelum submit PTK atau artikel jurnal. Banyak guru mengabaikan tahap ini atau melakukannya sendiri yang cenderung kurang objektif. AI dapat menjadi proofreader tangguh yang mendeteksi kesalahan tata bahasa, ejaan, tanda baca, dan konsistensi gaya penulisan. AI juga dapat menyesuaikan bahasa menjadi tata bahasa akademik baku yang lebih formal, konsisten, dan sesuai standar penulisan ilmiah. Menggunakan AI sebagai editor membantu guru menghasilkan teks yang lebih polished dan siap publikasi.</p>
        <p>Cara menggunakan AI sebagai proofreader: (1) salin teks yang ingin diedit; (2) beri instruksi jelas, misalnya "perbaiki tata bahasa, ejaan, dan buat gaya bahasa akademik baku tanpa mengubah makna"; (3) tinjau hasil editing, terima perubahan yang relevan, dan tolak yang mengubah makna; (4) ulangi proses jika perlu untuk paragraf lain. AI juga dapat membantu menyelaraskan konsistensi istilah, format sitasi, dan struktur kalimat. Namun, guru tetap harus membaca ulang hasil editing untuk memastikan akurasi konten dan tidak ada kesalahan yang masuk.</p>
        <p>Contoh instruksi proofreading ke AI: "Perbaiki tata bahasa dan ejaan teks berikut menjadi bahasa Indonesia akademik baku: [tempel teks]" – "Pastikan konsistensi istilah: gunakan 'siswa' bukan 'murid', dan 'guru' bukan 'pengajar'." – "Perbaiki kalimat pasif yang berlebihan menjadi kalimat aktif tanpa mengubah makna." – "Cek konsistensi format sitasi: semua referensi harus dalam format APA edisi ke-7." Contoh hasil editing: Sebelum: "siswa jadi lebih aktif karena guru kasih metode diskusi" – Sesudah: "Siswa menjadi lebih aktif karena guru menerapkan metode diskusi." Dengan AI sebagai proofreader, guru menghemat waktu dan menghasilkan teks yang lebih profesional, akurat, dan siap publikasi.</p>
    </div>
</div>