<!-- 8-6: Membantu Menganalisis Data Hasil Penelitian (Statistik Deskriptif Dasar via AI) -->
<div class="mb-20">
    <img src="https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=1200" alt="Analisis data" class="w-full h-[400px] md:h-[500px] object-cover rounded-3xl shadow-xl mb-8">
    <h2 class="text-3xl md:text-4xl font-extrabold text-slate-800 mb-6"><i class="fas fa-chart-line mr-3 text-orange-500"></i>8-6. Membantu Menganalisis Data Hasil Penelitian (Statistik Deskriptif Dasar via AI)</h2>
    <div class="prose prose-lg prose-slate max-w-none text-slate-600 leading-relaxed">
        <p>Analisis data PTK tidak harus rumit; statistik deskriptif dasar sering kali sudah cukup untuk menunjukkan perubahan atau peningkatan setelah intervensi. Statistik deskriptif meliputi: rata-rata, median, modus, persentase, standar deviasi, dan grafik sederhana. AI dapat membantu guru menghitung statistik ini dengan cepat jika guru menyediakan data mentah (misalnya nilai siswa sebelum dan sesudah intervensi, atau skor observasi). Analisis yang jelas dan terpresentasi dengan baik membuat hasil penelitian lebih meyakinkan dan mudah dipahami.</p>
        <p>Langkah analisis data via AI: (1) siapkan data dalam format terstruktur (tabel CSV atau Excel); (2) masukkan data ke AI dengan instruksi jelas, misalnya "hitung rata-rata, median, dan persentase peningkatan"; (3) minta AI membuat interpretasi singkat dari hasil statistik; (4) visualisasikan data dalam grafik batang atau garis untuk menunjukkan tren. AI juga dapat membantu membandingkan hasil antar siklus, misalnya "bandingkan rata-rata keaktifan Siklus 1 dan Siklus 2, lalu berikan interpretasi".</p>
        <p>Contoh analisis statistik deskriptif: Data Nilai Siswa (Siklus 1 vs Siklus 2) – Siklus 1: Rata-rata 65, Median 64, Standar Deviasi 8, Persentase KKM (≥70) = 40% – Siklus 2: Rata-rata 78, Median 77, Standar Deviasi 7, Persentase KKM (≥70) = 85%. Interpretasi: "Terjadi peningkatan signifikan dari Siklus 1 ke Siklus 2. Rata-rata meningkat 13 poin (20%), dan persentase siswa mencapai KKM meningkat dari 40% menjadi 85%. Standar deviasi menurun, menunjukkan konsistensi hasil yang lebih baik." Visualisasi: Grafik batang membandingkan rata-rata nilai Siklus 1 dan Siklus 2. Dengan bantuan AI untuk analisis statistik deskriptif, guru dapat menyajikan hasil PTK secara objektif, jelas, dan meyakinkan.</p>
    </div>
</div>