<!-- 8-1: Brainstorming Ide Judul PTK yang Valid Berdasarkan Permasalahan Nyata di Kelas Anda -->
<div class="mb-20">
    <img src="https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=80&w=1200" alt="Brainstorming ide PTK" class="w-full h-[400px] md:h-[500px] object-cover rounded-3xl shadow-xl mb-8">
    <h2 class="text-3xl md:text-4xl font-extrabold text-slate-800 mb-6"><i class="fas fa-lightbulb mr-3 text-yellow-500"></i>8-1. Brainstorming Ide Judul PTK yang Valid Berdasarkan Permasalahan Nyata di Kelas Anda</h2>
    <div class="prose prose-lg prose-slate max-w-none text-slate-600 leading-relaxed">
        <p>Judul PTK yang valid bermula dari permasalahan nyata yang dihadapi guru di kelas, bukan dari tren atau ide abstrak. Proses brainstorming ide judul dimulai dengan refleksi mendalam: masalah apa yang paling sering muncul, siswa bagian mana yang paling membutuhkan bantuan, atau strategi apa yang belum berhasil optimal. Ketika judul PTK didasarkan pada masalah nyata, penelitian menjadi lebih relevan, implementasinya lebih mudah, dan hasilnya lebih berdampak langsung pada kualitas pembelajaran. Guru tidak perlu mencari masalah yang megah; masalah sederhana yang konsisten dan terukur sudah cukup untuk menjadi dasar PTK yang berkualitas.</p>
        <p>Dalam brainstorming, guru dapat menuliskan 5–10 masalah yang dirasakan di kelas, lalu memfilternya berdasarkan kriteria: (1) masalah dapat diamati dan diukur; (2) masalah berada dalam kendali guru untuk diubah; (3) solusi yang diusulkan realistis untuk diimplementasikan; (4) hasil penelitian dapat dievaluasi. Dari daftar masalah tersebut, guru merumuskan judul PTK yang spesifik, mencakup variabel tindakan, subjek, dan konteks. Judul yang baik tidak terlalu panjang, tetapi cukup deskriptif untuk menggambarkan inti penelitian.</p>
        <p>Contoh rumusan judul PTK yang valid: "Penerapan Metode Diskusi Kelompok untuk Meningkatkan Keaktifan Siswa Kelas VIII SMP pada Mata Pelajaran IPS" – "Penggunaan Media Visual Infografis untuk Meningkatkan Pemahaman Konsep Ekonomi Siswa Kelas X SMA" – "Implementasi Teknik Feedback Tertulis untuk Meningkatkan Kualitas Karya Tulis Siswa Kelas V SD" – "Penerapan Sistem Reward Non-Material untuk Meningkatkan Motivasi Belajar Siswa Kelas VII SMP". Dengan brainstorming berbasis masalah nyata, guru menghasilkan judul PTK yang valid, relevan, dan siap diimplementasikan.</p>
    </div>
</div>