<!-- 8-8: Teknik Parafrase Etis Menggunakan AI agar Teks Terhindar dari Deteksi Plagiarisme (Turnitin) -->
<div class="mb-20">
    <img src="https://images.unsplash.com/photo-1589998059171-988d887df646?auto=format&fit=crop&q=80&w=1200" alt="Parafrase etis" class="w-full h-[400px] md:h-[500px] object-cover rounded-3xl shadow-xl mb-8">
    <h2 class="text-3xl md:text-4xl font-extrabold text-slate-800 mb-6"><i class="fas fa-pen-fancy mr-3 text-red-500"></i>8-8. Teknik Parafrase Etis Menggunakan AI agar Teks Terhindar dari Deteksi Plagiarisme (Turnitin)</h2>
    <div class="prose prose-lg prose-slate max-w-none text-slate-600 leading-relaxed">
        <p>Parafrase etis adalah keterampilan penting untuk menggunakan sumber literatur tanpa plagiat. Parafrase yang baik tidak hanya mengganti beberapa kata, tetapi mengubah struktur kalimat, urutan ide, dan gaya bahasa sambil mempertahankan makna asli dan mencantumkan sumber. AI dapat membantu parafrase dengan cepat, tetapi guru harus tetap mengawasi agar makna tidak berubah dan sumber tetap dicantumkan. Parafrase etis bukan untuk mengelabui detektor plagiarisme seperti Turnitin, tetapi untuk menyintesis ide orang lain dengan bahasa sendiri secara bertanggung jawab.</p>
        <p>Teknik parafrase etis menggunakan AI: (1) baca sumber asli hingga paham; (2) tutup sumber dan tulis ulang ide dengan bahasa sendiri; (3) gunakan AI untuk membandingkan versi Anda dengan sumber asli, lalu minta AI menyarankan perbaikan struktur tanpa mengubah makna; (4) pastikan semua ide yang bukan milik Anda dicantumkan sitasinya; (5) periksa hasil akhir dengan Turnitin atau alat plagiarism checker lainnya. Hindari copy-paste langsung dari AI; AI hanya alat bantu, bukan pengganti pemikiran kritis guru.</p>
        <p>Contoh parafrase etis: Teks Asli: "Metode diskusi kelompok efektif meningkatkan keaktifan siswa karena siswa terlibat aktif dalam proses belajar dan saling berbagi ide." [Smith, 2023] – Parafrase Tidak Etis (Hanya Ganti Kata): "Cara diskusi kelompok bagus menaikkan keaktifan siswa sebab siswa ikut aktif dalam proses belajar dan saling bagi ide." [Tetap plagiat] – Parafrase Etis: "Menurut Smith (2023), keterlibatan siswa dalam diskusi kelompok mendorong partisipasi aktif karena mereka saling bertukar ide selama proses pembelajaran." Dengan parafrase etis dan sitasi yang tepat, guru menghindari plagiarisme dan menghargai karya orang lain secara profesional.</p>
    </div>
</div>