<!-- 8-3: Trik Mencari dan Merangkum Literatur Teori / Kajian Pustaka Pendukung dengan Cepat -->
<div class="mb-20">
    <img src="https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&q=80&w=1200" alt="Kajian pustaka" class="w-full h-[400px] md:h-[500px] object-cover rounded-3xl shadow-xl mb-8">
    <h2 class="text-3xl md:text-4xl font-extrabold text-slate-800 mb-6"><i class="fas fa-book-open mr-3 text-green-500"></i>8-3. Trik Mencari dan Merangkum Literatur Teori / Kajian Pustaka Pendukung dengan Cepat</h2>
    <div class="prose prose-lg prose-slate max-w-none text-slate-600 leading-relaxed">
        <p>Kajian pustaka yang kuat mendukung validitas teoritis PTK, tetapi banyak guru kesulitan mencari dan merangkum literatur dalam waktu terbatas. Trik efektif adalah menggunakan kata kunci spesifik yang menggabungkan variabel penelitian, konteks, dan metode. Misalnya, untuk PTK tentang "diskusi kelompok meningkatkan keaktifan", kata kuncinya: "group discussion student activity classroom", "collaborative learning participation junior high", atau "diskusi kelompok keaktifan siswa SMP". Gunakan database akademik seperti Google Scholar, ERIC, atau ResearchGate, dan batasi pencarian pada 5–10 tahun terakhir untuk relevansi.</p>
        <p>Setelah menemukan literatur yang relevan, fokus pada abstrak, pendahuluan, dan kesimpulan untuk memahami inti penelitian. Gunakan AI untuk merangkum artikel panjang menjadi poin-poin kunci: teori utama, metode yang digunakan, hasil utama, dan implikasi. Rangkuman yang baik mencakup: (1) tujuan penelitian sebelumnya; (2) teori atau konsep yang digunakan; (3) metode dan sampel; (4) temuan utama; (5) relevansi dengan PTK Anda. Jangan menyalin langsung; parafrase dengan bahasa sendiri dan cantumkan sumber.</p>
        <p>Contoh format rangkuman literatur: Judul: "The Impact of Group Discussion on Student Participation" – Penulis/Tahun: Smith & Lee (2023) – Tujuan: Menguji efektivitas diskusi kelompok terhadap keaktifan siswa SMP. – Teori: Constructivist learning theory, collaborative learning. – Metode: PTK 2 siklus, 30 siswa, observasi dan kuesioner. – Hasil: Keaktifan siswa meningkat 45% setelah intervensi. – Relevansi: Mendukung hipotesis bahwa diskusi kelompok meningkatkan partisipasi siswa di kelas IPS. Dengan trik pencarian dan rangkuman yang efisien, guru dapat menyusun kajian pustaka yang kuat tanpa menghabiskan waktu berhari-hari.</p>
    </div>
</div>