<!-- 8-5: Membuat Instrumen Penelitian Sekejap (Lembar Observasi, Kuesioner, Pedoman Wawancara) -->
<div class="mb-20">
    <img src="https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&q=80&w=1200" alt="Instrumen penelitian" class="w-full h-[400px] md:h-[500px] object-cover rounded-3xl shadow-xl mb-8">
    <h2 class="text-3xl md:text-4xl font-extrabold text-slate-800 mb-6"><i class="fas fa-clipboard-list mr-3 text-indigo-500"></i>8-5. Membuat Instrumen Penelitian Sekejap (Lembar Observasi, Kuesioner, Pedoman Wawancara)</h2>
    <div class="prose prose-lg prose-slate max-w-none text-slate-600 leading-relaxed">
        <p>Instrumen penelitian yang valid dan reliabel adalah kunci untuk mengumpulkan data yang akurat. Banyak guru merasa kesulitan membuat instrumen dari nol, tetapi sebenarnya instrumen dapat dibuat dengan cepat menggunakan template standar yang disesuaikan dengan konteks penelitian. Lembar observasi fokus pada perilaku yang dapat diamati, kuesioner mengukur persepsi atau sikap, dan pedoman wawancara menggali informasi mendalam. Instrumen yang baik sederhana, jelas, dan langsung terkait dengan variabel penelitian.</p>
        <p>Untuk membuat lembar observasi sekejap, tentukan dulu perilaku atau indikator yang ingin diamati, lalu buat checklist atau skala rating. Untuk kuesioner, gunakan skala Likert (1–5) dengan pernyataan positif dan negatif yang seimbang. Untuk pedoman wawancara, siapkan 5–10 pertanyaan terbuka yang menggali pengalaman, perasaan, atau persepsi responden. AI dapat membantu merancang instrumen dengan memberikan variabel penelitian dan konteks, lalu guru menyempurnakannya agar sesuai dengan karakteristik siswa.</p>
        <p>Contoh instrumen cepat: Lembar Observasi Keaktifan Siswa – Indikator: (1) Mengangkat tangan untuk bertanya, (2) Memberikan pendapat dalam diskusi, (3) Menjawab pertanyaan guru, (4) Bekerja sama dalam kelompok. Skala: 0 = Tidak pernah, 1 = Kadang-kadang, 2 = Sering, 3 = Selalu. Kuesioner Motivasi Belajar (Skala Likert 1–5): "Saya merasa antusias saat pelajaran dimulai." "Saya berusaha menyelesaikan tugas meskipun sulit." "Saya merasa pembelajaran ini bermanfaat bagi saya." Pedoman Wawancara: "Apa yang membuatmu merasa senang/susah saat mengikuti pelajaran?" "Bagaimana perasaanmu saat diskusi kelompok?" "Apa yang bisa membuatmu lebih aktif dalam kelas?" Dengan instrumen yang dirancang cepat namun valid, guru dapat mengumpulkan data PTK secara efisien dan akurat.</p>
    </div>
</div>