<!-- 8-9: Merumuskan Kesimpulan dan Saran Penelitian yang Actionable Secara Komprehensif -->
<div class="mb-20">
    <img src="https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&q=80&w=1200" alt="Kesimpulan dan saran" class="w-full h-[400px] md:h-[500px] object-cover rounded-3xl shadow-xl mb-8">
    <h2 class="text-3xl md:text-4xl font-extrabold text-slate-800 mb-6"><i class="fas fa-check-double mr-3 text-emerald-500"></i>8-9. Merumuskan Kesimpulan dan Saran Penelitian yang Actionable Secara Komprehensif</h2>
    <div class="prose prose-lg prose-slate max-w-none text-slate-600 leading-relaxed">
        <p>Kesimpulan dan saran adalah bagian yang paling dibaca oleh praktisi karena berisi inti temuan dan rekomendasi yang dapat diterapkan. Kesimpulan yang baik merangkum temuan utama secara objektif, menjawab rumusan masalah, dan menunjukkan dampak intervensi tanpa berlebihan. Saran yang actionable memberikan rekomendasi konkret untuk guru lain, peneliti berikutnya, atau kebijakan sekolah. Kesimpulan dan saran yang komprehensif meningkatkan nilai praktis PTK dan membuka peluang untuk publikasi atau diseminasi.</p>
        <p>Struktur kesimpulan yang efektif: (1) ringkasan singkat tujuan penelitian; (2) temuan utama dalam bentuk poin atau paragraf singkat; (3) jawaban atas rumusan masalah; (4) implikasi praktis untuk pembelajaran. Struktur saran yang efektif: (1) saran untuk guru/praktisi (apa yang bisa diterapkan); (2) saran untuk peneliti berikutnya (apa yang bisa diteliti lebih lanjut); (3) saran untuk kebijakan sekolah (jika relevan). Hindari saran yang terlalu umum seperti "perlu penelitian lebih lanjut"; buat saran spesifik dan dapat ditindaklanjuti.</p>
        <p>Contoh rumusan kesimpulan dan saran: Kesimpulan: "Penelitian ini menyimpulkan bahwa penerapan metode diskusi kelompok secara signifikan meningkatkan keaktifan siswa Kelas VIII-A. Keaktifan meningkat dari 30% pada pra-siklus menjadi 85% pada Siklus 2. Temuan ini mendukung hipotesis bahwa diskusi kelompok efektif untuk pembelajaran IPS." Saran untuk Praktisi: "Guru IPS disarankan menerapkan diskusi kelompok dengan penugasan peran jelas (ketua, notulen, presenter) untuk memaksimalkan keaktifan semua siswa." Saran untuk Peneliti Berikutnya: "Penelitian lanjutan dapat menguji efektivitas diskusi kelompok pada mata pelajaran lain atau pada siswa dengan karakteristik berbeda." Saran untuk Kebijakan Sekolah: "Sekolah dapat menyediakan pelatihan diskusi kelompok bagi guru untuk meningkatkan kualitas pembelajaran kolaboratif." Dengan kesimpulan dan saran yang actionable, PTK menjadi lebih bernilai praktis dan mudah direplikasi oleh guru lain.</p>
    </div>
</div>