<!-- 8-2: Merumuskan Latar Belakang Masalah Secara Tajam, Terstruktur, dan Akademis -->
<div class="mb-20">
    <img src="https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&q=80&w=1200" alt="Latar belakang masalah" class="w-full h-[400px] md:h-[500px] object-cover rounded-3xl shadow-xl mb-8">
    <h2 class="text-3xl md:text-4xl font-extrabold text-slate-800 mb-6"><i class="fas fa-pencil-ruler mr-3 text-blue-500"></i>8-2. Merumuskan Latar Belakang Masalah Secara Tajam, Terstruktur, dan Akademis</h2>
    <div class="prose prose-lg prose-slate max-w-none text-slate-600 leading-relaxed">
        <p>Latar belakang masalah adalah fondasi yang menentukan kualitas seluruh PTK. Latar belakang yang tajam dan terstruktur membacakan alur logis: dari konteks umum, menuju masalah spesifik, menunjukkan urgensi, lalu mengakhiri dengan tujuan penelitian. Latar belakang yang akademis menggunakan bahasa formal, didukung data atau observasi awal, dan menghindari opini subjektif tanpa bukti. Ketika latar belakang ditulis dengan baik, pembaca (termasuk reviewer jurnal) langsung memahami mengapa penelitian ini penting dan layak dilakukan.</p>
        <p>Struktur latar belakang yang efektif terdiri dari: (1) konteks umum tentang bidang pembelajaran atau mata pelajaran; (2) data atau fakta yang menunjukkan adanya masalah (bisa dari nilai, observasi, atau pengalaman guru); (3) dampak negatif jika masalah tidak ditangani; (4) solusi yang diusulkan secara singkat; (5) tujuan penelitian. Hindari latar belakang yang terlalu panjang atau bertele-tele; fokus pada alur logis yang jelas. Gunakan paragraf pendek, kalimat aktif, dan hindari klise yang tidak didukung data.</p>
        <p>Contoh alur latar belakang: Paragraf 1 (Konteks): "Pembelajaran IPS di SMP menuntut siswa tidak hanya menghafal fakta, tetapi juga mampu menganalisis fenomena sosial. Namun, realitas di kelas menunjukkan banyak siswa masih pasif dalam diskusi." Paragraf 2 (Masalah & Data): "Berdasarkan observasi awal di Kelas VIII-A, hanya 30% siswa yang aktif berkontribusi saat diskusi kelompok. Nilai rata-rata pertanyaan analitis juga masih di bawah KKM." Paragraf 3 (Urgensi & Tujuan): "Kondisi ini menghambat pengembangan keterampilan berpikir kritis siswa. Penelitian ini bertujuan untuk menguji efektivitas metode diskusi kelompok dalam meningkatkan keaktifan siswa." Dengan latar belakang yang tajam dan terstruktur, PTK menjadi lebih kredibel dan persuasif.</p>
    </div>
</div>
