<!-- SLIDE 1 -->
<div class="mb-20">
    <img src="https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&q=80&w=1200" alt="Guru Super" class="w-full h-[400px] md:h-[500px] object-cover rounded-3xl shadow-xl mb-8">
    <h2 class="text-3xl md:text-4xl font-extrabold text-slate-800 mb-6"><i class="fas fa-layer-group mr-3 text-blue-500"></i>Berdiferensiasi: Mitos Super-Guru Berkepala Tiga</h2>
    <div class="prose prose-lg prose-slate max-w-none text-slate-600 leading-relaxed">
        <p>Ketika wacana Pembelajaran Berdiferensiasi pertama kali digulirkan, banyak guru yang panik dan merasakannya sebagai horor administratif terbesar di abad ini. Mitos yang beredar luas di ruang guru adalah: "Jika di kelas saya ada murid yang pintar, sedang, dan lambat, apakah ini berarti saya dituntut untuk membuat 3 Modul Ajar (RPP) yang berbeda, mengajar 3 bab yang berbeda, dengan 3 macam ujian yang juga berbeda secara bersamaan?!" Jika cara kerjanya memang demikian, seorang guru butuh 72 jam sehari hanya untuk bertahan hidup.</p>
        <p>Fakta pedagogis yang sebenarnya jauh lebih masuk akal. Diferensiasi bukanlah tentang mengajarkan materi yang berbeda-beda dalam satu waktu. Tujuan akhir pembelajaran (TP) yang ingin dicapai tetaplah SATU. Diferensiasi adalah tentang cara kita membedakan "jalan raya" atau rute yang ditempuh siswa untuk mencapai tujuan tunggal tersebut. Kita bisa merancangnya melalui tiga aspek utama: Diferensiasi Konten (apa bentuk materi yang diserap), Diferensiasi Proses (bagaimana aktivitas mereka memproses materi), dan Diferensiasi Produk (bagaimana wujud karya mereka membuktikan pemahaman).</p>
        <p>Meski konsepnya terdengar indah di atas kertas, menyusun tiga skenario aktivitas yang relevan dan saling melengkapi secara manual tetap saja membutuhkan curahan tenaga dan perasan otak yang tidak sedikit. Di sinilah Prompt Engineering membuktikan dirinya sebagai asisten kurikulum yang paling tangguh. Hanya dengan memberikan satu instruksi detail berbasis data asesmen awal kelas Anda, AI mampu membelah satu materi yang sama menjadi ragam opsi aktivitas belajar yang menyenangkan dan pas dengan porsi setiap anak.</p>
    </div>
</div>

<!-- SLIDE 2 -->
<div class="mb-20">
    <img src="https://images.unsplash.com/photo-1636466497217-26a8cbeaf0aa?auto=format&fit=crop&q=80&w=1200" alt="Kesiapan Belajar" class="w-full h-[400px] md:h-[500px] object-cover rounded-3xl shadow-xl mb-8">
    <h2 class="text-3xl md:text-4xl font-extrabold text-slate-800 mb-6"><i class="fas fa-signal mr-3 text-emerald-500"></i>Diferensiasi Proses Berdasarkan Kesiapan (Readiness)</h2>
    <div class="prose prose-lg prose-slate max-w-none text-slate-600 leading-relaxed">
        <p>Pendekatan paling esensial dalam diferensiasi adalah mengelompokkan siswa berdasarkan Kesiapan Belajar (Readiness). Bayangkan Anda sedang mengajarkan materi Persamaan Linear di pelajaran Matematika. Setelah memberikan tes diagnostik ringan (Pre-test) di awal minggu, Anda menemukan fakta lapangan bahwa kelas Anda terpecah menjadi tiga kelompok yang sangat kontras: Kelompok A yang sudah mahir dan bosan, Kelompok B yang paham dasarnya namun butuh latihan, dan Kelompok C yang masih kebingungan menebak variabel dasar.</p>
        <p>Mempresentasikan materi yang sama dengan ritme yang sama untuk ketiga kelompok ini adalah resep menuju kelas yang kacau. Buka AI Anda dan berikan konteks ini secara spesifik: "Saya mengajar Persamaan Linear 1 Variabel. Berdasarkan data asesmen awal, kelas terbagi 3 tingkat kesiapan. Tolong rancangkan aktivitas Diferensiasi PROSES untuk masing-masing kelompok secara spesifik. Untuk Kelompok C (Pemula), rancang aktivitas <i>scaffolding</i> yang sangat dipandu. Untuk Kelompok B (Menengah), buatkan panduan latihan <i>peer-tutoring</i>. Untuk Kelompok A (Mahir), rancang 1 tantangan pengayaan studi kasus dunia nyata."</p>
        <p>Berkat arahan <i>prompt</i> ini, AI tidak hanya memunculkan ide generik, melainkan merumuskan tugas bertingkat. Siswa di Kelompok A mungkin disuruh oleh AI untuk menghitung budget proyek sekolah menggunakan aljabar (membuat mereka merasa tertantang dan tidak mengganggu kelas), sementara Anda, sang guru, bisa fokus memberikan waktu dan perhatian ekstra di meja Kelompok C untuk membimbing mereka perlahan dengan alat peraga konkret tanpa interupsi. Ini adalah orkestrasi kelas yang harmonis.</p>
    </div>
</div>

<!-- SLIDE 3 -->
<div class="mb-20">
    <img src="https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?auto=format&fit=crop&q=80&w=1200" alt="Minat Siswa" class="w-full h-[400px] md:h-[500px] object-cover rounded-3xl shadow-xl mb-8">
    <h2 class="text-3xl md:text-4xl font-extrabold text-slate-800 mb-6"><i class="fas fa-heart mr-3 text-rose-500"></i>Diferensiasi Konten & Produk Berdasarkan Minat</h2>
    <div class="prose prose-lg prose-slate max-w-none text-slate-600 leading-relaxed">
        <p>Jika diferensiasi kesiapan fokus pada kemampuan otak, maka Diferensiasi Minat (Interest) adalah strategi untuk merebut hati dan perhatian siswa. Anak-anak masa kini memiliki hobi dan referensi kultur pop yang sangat beragam: ada kelompok *gamers* sejati, kelompok anak basket yang tak bisa diam, geng pecinta K-Pop, hingga anak-anak *introvert* yang hobi menggambar manga. Sebagai pendidik, kita bisa mendompleng ketertarikan alami mereka ini sebagai "kendaraan" untuk menyelundupkan konsep-konsep akademis yang sulit.</p>
        <p>Misalnya, Anda menargetkan materi Biologi tentang Pewarisan Sifat (Genetika). Anda bisa merancang prompt: "Tujuan pembelajaran hari ini adalah agar siswa menguasai konsep dasar Pewarisan Sifat. Tolong buatkan ide Diferensiasi KONTEN & PRODUK berdasarkan 3 klaster minat dominan di kelas saya: 1) Pecinta Olahraga Bola, 2) Pecinta Seni/Komik, dan 3) Pecinta Hewan. Jelaskan bagaimana saya bisa menggunakan analogi dari ketiga hobi ini untuk menjelaskan genetik. Kemudian, berikan 3 Opsi Tugas Akhir berbeda agar mereka bisa membuktikan pemahamannya."</p>
        <p>Hasil <i>output</i> AI akan sangat menakjubkan. Anak basket mungkin akan ditugaskan menganalisis probabilitas genetik profil fisik atlet NBA; anak pecinta hewan akan antusias membuat bagan persilangan ras kucing favorit mereka; dan anak seni akan menggambar komik tentang perjalanan sebuah sel DNA. Ketika ujian akhir tidak lagi terpaku pada satu metode evaluasi tertulis, melainkan pada proyek yang menyala oleh *passion* murid, Anda akan melihat kelas yang hiperfokus dan minim pelanggaran disiplin karena setiap anak merasa difasilitasi.</p>
    </div>
</div>

<!-- SLIDE 4 -->
<div class="mb-20">
    <img src="https://images.unsplash.com/photo-1573164574572-cb89e39749b4?auto=format&fit=crop&q=80&w=1200" alt="Gaya Belajar" class="w-full h-[400px] md:h-[500px] object-cover rounded-3xl shadow-xl mb-8">
    <h2 class="text-3xl md:text-4xl font-extrabold text-slate-800 mb-6"><i class="fas fa-headphones-alt mr-3 text-amber-500"></i>Rotasi Pos (Station Rotation) Berbasis Gaya Belajar</h2>
    <div class="prose prose-lg prose-slate max-w-none text-slate-600 leading-relaxed">
        <p>Dari kacamata sains kognitif modern, mengotak-ngotakkan siswa secara kaku ke dalam label Visual, Auditori, atau Kinestetik (VAK) seumur hidupnya sebenarnya mulai ditinggalkan. Manusia pada dasarnya belajar secara campuran atau multimodal. Meskipun demikian, merancang pengalaman belajar di dalam kelas yang secara bergantian merangsang ketiga indera panca tersebut tetaplah sebuah metode pedagogi tingkat tinggi yang akan menghilangkan kebosanan murid yang jenuh duduk diam selama berjam-jam.</p>
        <p>Pendekatan fisik terbaik untuk mewadahi ini adalah metode <i>Station Rotation</i> (Rotasi Pos), di mana Anda membagi sudut-sudut kelas menjadi beberapa stasiun aktivitas yang berbeda, dan kelompok siswa bergerak berpindah stasiun setiap 15 menit. Anda bisa menyuruh AI menjadi perancang kegiatan pos tersebut: "Rancang metode Station Rotation untuk materi IPA Sistem Tata Surya. Buat 3 Pos aktivitas: Pos 1 fokus pada kekuatan Visual (literasi mandiri/infografis), Pos 2 fokus Auditori (diskusi audio/podcast/debat kelompok kecil), dan Pos 3 wajib Kinestetik (kegiatan taktil/merakit model 3D). Jelaskan alur rotasi dan kebutuhan materinya."</p>
        <p>Desain instruksional yang dihasilkan AI akan memastikan bahwa setiap pos memiliki tugas mandiri yang terstruktur jelas, sehingga rotasi tidak berakhir menjadi *chaos* tak terkendali. Murid akan merasakan dinamika belajar yang sangat kaya, menyerap informasi dengan membaca, mendengar, berbicara, dan menyentuh sekaligus dalam satu jam pelajaran. Guru tidak lagi berceramah di depan kelas, melainkan bertransformasi menjadi fasilitator mobilitas yang elegan, memantau *flow* atau aliran energi murid dari satu pos ke pos lainnya.</p>
    </div>
</div>

<!-- SLIDE 5 -->
<div class="mb-20">
    <img src="https://images.unsplash.com/photo-1542744173-8e7e53415bb0?auto=format&fit=crop&q=80&w=1200" alt="Matriks Checklist" class="w-full h-[400px] md:h-[500px] object-cover rounded-3xl shadow-xl mb-8">
    <h2 class="text-3xl md:text-4xl font-extrabold text-slate-800 mb-6"><i class="fas fa-clipboard-list mr-3 text-emerald-500"></i>Matriks Diferensiasi (Checklist Eksekutif)</h2>
    <div class="prose prose-lg prose-slate max-w-none text-slate-600 leading-relaxed">
        <p>Ide-ide brilian tentang diferensiasi kesiapan, minat, dan rotasi pos yang dikeluarkan oleh AI sering kali berupa teks panjang yang menjabarkan teori demi teori. Meski sangat bagus untuk memperluas cakrawala pemahaman Anda sebagai pendidik, teks narasi yang panjang ini sangat tidak efisien jika harus diprint dan diselipkan ke dalam dokumen Modul Ajar (RPP) formal yang akan diperiksa oleh sekolah atau dinas pendidikan. Anda membutuhkan ringkasan taktis yang terlihat rapi dan profesional secara administratif.</p>
        <p>Untuk menyatukan semua inovasi kreatif tersebut ke dalam bingkai birokrasi, biasakan untuk selalu merangkum akhir percakapan AI Anda dengan permintaan tabel matriks. Gunakan instruksi tegas: "Rangkum seluruh ide strategi diferensiasi yang baru saja kita diskusikan ke dalam satu Matriks Checklist Eksekutif. Buat format tabel dengan kolom: Jenis Diferensiasi, Dasar Pemetaan (Kesiapan/Minat), Deskripsi Aktivitas Singkat, dan Peran Spesifik Guru. Buat narasi seringkas mungkin agar muat di-<i>print</i> dalam satu halaman lampiran."</p>
        <p>Hasil cetakan tabel matriks ini akan menjadi dokumen "senjata pamungkas" Anda. Ketika Pengawas Sekolah atau Kepala Sekolah melakukan supervisi kelas dan membolak-balik dokumen RPP Anda, mereka akan langsung terpukau melihat struktur tabel yang rapi, yang merinci setiap keputusan pedagogis yang Anda ambil demi mewadahi keberagaman murid. Anda tidak hanya mengajar dengan luar biasa di lapangan, tetapi juga memiliki bukti dokumentasi administrasi level eksekutif yang tak terbantahkan, semuanya dengan sedikit bantuan teknis dari AI.</p>
    </div>
</div>