<div class="mb-20">
    <img src="https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&q=80&w=1200" alt="Cyber Security Etika" class="w-full h-[400px] md:h-[500px] object-cover rounded-3xl shadow-xl mb-8">
    <h2 class="text-3xl md:text-4xl font-extrabold text-slate-800 mb-6"><i class="fas fa-shield-alt mr-3 text-red-500"></i>Sisi Gelap AI: Literasi Digital yang Wajib Masuk Kurikulum</h2>
    <div class="prose prose-lg prose-slate max-w-none text-slate-600 leading-relaxed">
        <p>Di balik gemerlap kemudahan yang ditawarkan oleh AI Generatif, tersimpan sebuah jurang etika yang sangat dalam jika kita tidak membekali diri dengan kedewasaan kognitif. Teknologi AI itu ibarat sebuah "Pisau Bedah Laser"; di tangan seorang ahli bedah yang paham anatomi, ia adalah alat mukjizat untuk menyembuhkan, namun di tangan balita, ia adalah senjata mematikan. Masalah utama yang sering muncul adalah **Bias Algoritma**. AI dilatih menggunakan data dari internet yang sudah terkontaminasi oleh prasangka manusia selama berabad-abad. Jika internet penuh dengan stereotip gender, rasisme, atau ketimpangan sejarah, maka AI akan mewarisi "dosa" tersebut dan menyajikannya kembali dalam bentuk jawaban yang seolah-olah objektif, padahal sangat berpihak pada satu narasi dominan.</p>
        <p>Fenomena kedua yang harus dipahami guru adalah **Hallucination (Halusinasi AI)**. Penting untuk diingat bahwa AI tidak memiliki akses ke "kebenaran absolut"; ia hanya mesin prediksi probabilitas teks. Saat AI tidak tahu jawaban dari sebuah pertanyaan faktual, ia tidak akan mengaku kalah. Sebaliknya, karena ia diprogram untuk selalu "terdengar meyakinkan", AI akan mulai mengarang bebas dengan sangat rapi. Ia bisa menciptakan kutipan tokoh sejarah yang fiktif, merekayasa referensi jurnal medis palsu, hingga memberikan tautan URL bodong yang terlihat sangat valid. Hal ini menjadi tantangan besar dalam integritas akademik; kita tidak boleh memperlakukan AI sebagai ensiklopedia kebenaran, melainkan sebagai rekan diskusi yang pekerjaannya wajib kita verifikasi ulang secara manual.</p>
        <p>Terakhir, kita harus menyadari **Batasan Sistem** yang dimiliki AI. AI tidak memiliki hati nurani, nurani moral, atau pemahaman emosional otentik. Ia bisa memberikan solusi teknis yang efisien tetapi mungkin sangat tidak manusiawi jika diterapkan di kelas. Sebagai pendidik, peran kita adalah menjadi "Filter Etis". Tugas utama kita bukan lagi sekadar mengajarkan murid cara menggunakan alat ini, melainkan menanamkan literasi kritis: kapan mereka harus meragukan AI, bagaimana cara mendeteksi bias, dan bagaimana menjaga integritas diri di tengah banjir informasi artifisial. Literasi etika AI inilah yang akan menjadi tameng pertahanan hidup (survival skill) paling krusial bagi generasi masa depan di era silikon.</p>

    </div>
</div>