<!-- 7-9: Skenario Sesi Circle Time untuk Meningkatkan Kecerdasan Emosional (EQ) Siswa -->
<div class="mb-20">
    <img src="https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&q=80&w=1200" alt="Circle time" class="w-full h-[400px] md:h-[500px] object-cover rounded-3xl shadow-xl mb-8">
    <h2 class="text-3xl md:text-4xl font-extrabold text-slate-800 mb-6"><i class="fas fa-users mr-3 text-green-500"></i>7-9. Skenario Sesi Circle Time untuk Meningkatkan Kecerdasan Emosional (EQ) Siswa</h2>
    <div class="prose prose-lg prose-slate max-w-none text-slate-600 leading-relaxed">
        <p>Circle time adalah sesi terstruktur di mana siswa duduk melingkar dan berbagi pikiran, perasaan, atau pengalaman dalam lingkungan yang aman dan saling menghargai. Sesi ini sangat efektif untuk meningkatkan kecerdasan emosional (EQ) siswa, karena siswa belajar mengenali emosi diri, memahami perasaan orang lain, dan berlatih komunikasi asertif. Circle time juga membangun rasa kebersamaan, kepercayaan, dan empati di kelas. Guru berperan sebagai fasilitator yang menciptakan suasana nyaman, memastikan semua suara terdengar, dan menjaga norma diskusi yang positif.</p>
        <p>Skenario circle time yang efektif dimulai dengan ritual pembukaan (misalnya: salam, napas dalam, atau kalimat niat), diikuti oleh pertanyaan pemantik yang relevan dengan perkembangan sosial-emosional siswa. Pertanyaan harus terbuka, tidak mengancam, dan memungkinkan berbagai jawaban. Waktu bicara diatur adil, misalnya menggunakan benda bicara (batu bicara) yang hanya boleh dipegang oleh orang yang berbicara. Guru memodelkan empati, validasi emosi, dan refleksi. Sesi ditutup dengan ringkasan singkat dan kalimat penutup yang menguatkan.</p>
        <p>Contoh skenario circle time: <strong>Pembukaan:</strong> "Selamat pagi, teman-teman. Mari tarik napas dalam bersama… Kita duduk dalam lingkaran untuk saling mendengar dengan hati terbuka." <strong>Pertanyaan pemantik:</strong> "Apa satu emosi yang kamu rasakan hari ini, dan mengapa?" atau "Ceritakan momen saat kamu merasa bangga membantu teman." <strong>Norma:</strong> "Kita mendengarkan tanpa memotong, kita menghargai setiap cerita, dan apa yang dibagikan di sini tetap di dalam lingkaran." <strong>Penutup:</strong> "Terima kasih atas kejujuran kalian. Kita semua belajar dari satu sama lain. Sampai jumpa di circle time berikutnya!" Dengan circle time yang konsisten, guru membangun fondasi EQ yang kuat dan menciptakan budaya kelas yang empatik dan inklusif.</p>
    </div>
</div>