<!-- 7-10: Mengelola Kelelahan Guru (Burnout): Meminta AI Menjadi Mitra Diskusi Profesional -->
<div class="mb-20">
    <img src="https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&q=80&w=1200" alt="Guru burnout" class="w-full h-[400px] md:h-[500px] object-cover rounded-3xl shadow-xl mb-8">
    <h2 class="text-3xl md:text-4xl font-extrabold text-slate-800 mb-6"><i class="fas fa-brain mr-3 text-purple-500"></i>7-10. Mengelola Kelelahan Guru (Burnout): Meminta AI Menjadi Mitra Diskusi Profesional</h2>
    <div class="prose prose-lg prose-slate max-w-none text-slate-600 leading-relaxed">
        <p>Burnout pada guru adalah fenomena nyata yang berdampak pada kualitas pengajaran, kesehatan mental, dan hubungan dengan siswa. Mengelola burnout memerlukan kesadaran diri, strategi pemulihan, dan dukungan sosial. AI dapat menjadi mitra diskusi profesional yang aman, tidak menghakimi, dan selalu tersedia untuk guru yang ingin refleksi, mencari solusi, atau sekadar melegakan beban emosional. Diskusi dengan AI membantu guru mengidentifikasi sumber stres, merumuskan strategi coping, dan menemukan kembali makna dalam pekerjaan mengajar.</p>
        <p>Strategi mengelola burnout meliputi: (1) identifikasi tanda-tanda awal seperti kelelahan kronis, sinisme, atau penurunan motivasi; (2) tetapkan batas sehat antara pekerjaan dan kehidupan pribadi; (3) latihan self-care rutin (olahraga, tidur cukup, hobi); (4) cari dukungan dari rekan, atasan, atau konselor; (5) gunakan AI untuk refleksi terstruktur, seperti menuliskan stresor, menganalisis pola, dan merancang rencana tindakan. AI dapat membantu guru merumuskan pertanyaan reflektif, menyimulasikan percakapan sulit, atau menghasilkan ide strategi baru.</p>
        <p>Contoh pertanyaan reflektif untuk diskusi dengan AI: "Apa tiga sumber stres utama saya saat ini, dan bagaimana saya bisa menguranginya?" "Strategi apa yang bisa saya terapkan untuk menetapkan batas kerja yang lebih sehat?" "Bagaimana cara saya mengingat kembali mengapa saya memilih menjadi guru?" "Apa satu langkah kecil yang bisa saya lakukan hari ini untuk merawat diri sendiri?" Dengan menggunakan AI sebagai mitra diskusi dan menerapkan strategi self-care, guru dapat mencegah atau memulihkan burnout, serta tetap mengajar dengan semangat dan kehadiran yang utuh.</p>
    </div>
</div>