<!-- 7-4: Menyusun Naskah Ice Breaking dan Motivasi Pagi Harian yang Segar dan Relevan -->
<div class="mb-20">
    <img src="https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&q=80&w=1200" alt="Ice breaking kelas" class="w-full h-[400px] md:h-[500px] object-cover rounded-3xl shadow-xl mb-8">
    <h2 class="text-3xl md:text-4xl font-extrabold text-slate-800 mb-6"><i class="fas fa-smile-wink mr-3 text-yellow-500"></i>7-4. Menyusun Naskah Ice Breaking dan Motivasi Pagi Harian yang Segar dan Relevan</h2>
    <div class="prose prose-lg prose-slate max-w-none text-slate-600 leading-relaxed">
        <p>Ice breaking dan motivasi pagi adalah elemen penting untuk membangun energi positif di awal pembelajaran. Aktivitas ini tidak sekadar pengisi waktu, tetapi kesempatan untuk menyelaraskan suasana hati siswa, membangun koneksi sosial, dan menyiapkan mental untuk belajar. Ice breaking yang efektif singkat, menyenangkan, relevan dengan konteks pembelajaran atau kehidupan siswa, dan mudah diikuti oleh semua kalangan usia. Motivasi pagi yang segar harus menyentuh nilai-nilai personal seperti ketekunan, keberanian, kerja sama, atau rasa syukur, sehingga siswa merasa terinspirasi dan termotivasi.</p>
        <p>Untuk menyusun naskah ice breaking, guru dapat memilih tema harian (misalnya: kepercayaan diri, kerja tim, atau kreativitas), lalu merancang aktivitas 3–5 menit yang melibatkan gerakan fisik ringan, interaksi sosial, atau refleksi singkat. Motivasi pagi bisa disampaikan dalam bentuk cerita pendek, kutipan inspiratif, atau pertanyaan reflektif yang memicu pemikiran. Hindari pesan klise; sebaliknya, gunakan bahasa yang tulus, relate dengan pengalaman siswa, dan ajakan konkret untuk bertindak. Variasi setiap hari juga penting agar siswa tidak bosan dan tetap antusias.</p>
        <p>Contoh naskah singkat: <strong>Ice Breaking:</strong> "Hari ini kita bermain 'Lempar Bola Pertanyaan'. Saya lempar bola ke siapa saja, yang menangkap harus menjawab: 'Satu hal yang saya syukuri pagi ini adalah…'. Setelah itu, lempar ke teman lain." <strong>Motivasi Pagi:</strong> "Pagi hari ini, saya ingin mengingatkan kita semua: setiap kesalahan adalah kesempatan untuk belajar. Jangan takut mencoba hal baru. Hari ini, saya tunggu ide spektakuler dari kalian!" <strong>Kalimat penutup:</strong> "Siap membuat hari ini lebih baik dari kemarin? Ayo kita mulai dengan semangat!" Dengan rutin melaksanakan ice breaking dan motivasi pagi yang segar, guru menciptakan budaya kelas yang positif dan energik.</p>
    </div>
</div>