<!-- 7-1: Generator Narasi Evaluasi Rapor yang Positif, Personal, dan Tidak Kelihatan Template -->
<div class="mb-20">
    <img src="https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&q=80&w=1200" alt="Rapor siswa" class="w-full h-[400px] md:h-[500px] object-cover rounded-3xl shadow-xl mb-8">
    <h2 class="text-3xl md:text-4xl font-extrabold text-slate-800 mb-6"><i class="fas fa-pen-fancy mr-3 text-blue-500"></i>7-1. Generator Narasi Evaluasi Rapor yang Positif, Personal, dan Tidak Kelihatan Template</h2>
    <div class="prose prose-lg prose-slate max-w-none text-slate-600 leading-relaxed">
        <p>Menulis narasi evaluasi rapor yang terasa personal dan positif adalah keterampilan penting bagi guru humanis. Narasi rapor tidak boleh sekadar daftar pencapaian kaku; sebaliknya, narasi harus mencerminkan ketulusan, pemahaman mendalam terhadap perkembangan siswa, dan harapan yang membangun. Ketika guru menulis dengan nada hangat dan spesifik, orang tua dan siswa merasa dihargai sebagai individu, bukan hanya sebagai angka atau nilai. Narasi yang personal juga memperkuat hubungan kepercayaan antara guru, siswa, dan keluarga, yang pada akhirnya mendorong motivasi belajar siswa.</p>
        <p>Agar narasi rapor tidak terlihat seperti template, guru perlu memasukkan detail unik dari proses belajar siswa: kebiasaan positif yang muncul, usaha khusus yang dilakukan, atau momen breakthrough tertentu. Misalnya, daripada menulis "Ananda sudah meningkatkan kemampuan matematika", guru bisa menulis, "Ananda menunjukkan progres luar biasa dalam pemecahan soal cerita matematika; ia mulai berani mencoba pendekatan berbeda dan tidak mudah menyerah saat menghadapi soal yang menantang." Kalimat seperti ini menunjukkan observasi nyata dan memberikan pengakuan terhadap usaha siswa. AI dapat membantu guru menghasilkan variasi narasi yang tetap autentik dengan memberikan beberapa poin kunci tentang siswa, lalu guru menyempurnakannya dengan sentuhan personal.</p>
        <p>Berikut contoh kalimat yang bisa digunakan sebagai referensi: "Ananda menunjukkan semangat belajar yang konsisten, terutama saat bekerja dalam kelompok kecil; ia sering menjadi pendengar aktif dan memberikan ide yang konstruktif." "Meskipun awal semester Ananda masih ragu dalam presentasi, ia kini berani berbicara di depan kelas dengan percaya diri dan menyusun argumen yang jelas." "Saya sangat mengapresiasi ketekunan Ananda dalam menyelesaikan tugas-tugas proyek; ia selalu mengumpulkan tepat waktu dan menunjukkan perbaikan dari waktu ke waktu." Dengan menggabungkan observasi spesifik, pengakuan usaha, dan harapan yang membangun, guru dapat menghasilkan narasi rapor yang positif, personal, dan tidak terasa seperti copy-paste template.</p>
    </div>
</div>