<!-- 7-5: Merancang Tata Tertib Kelas yang Kolaboratif, Menggunakan Kalimat Positif (Bukan Larangan) -->
<div class="mb-20">
    <img src="https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&q=80&w=1200" alt="Tata tertib kelas" class="w-full h-[400px] md:h-[500px] object-cover rounded-3xl shadow-xl mb-8">
    <h2 class="text-3xl md:text-4xl font-extrabold text-slate-800 mb-6"><i class="fas fa-clipboard-list mr-3 text-indigo-500"></i>7-5. Merancang Tata Tertib Kelas yang Kolaboratif, Menggunakan Kalimat Positif (Bukan Larangan)</h2>
    <div class="prose prose-lg prose-slate max-w-none text-slate-600 leading-relaxed">
        <p>Tata tertib kelas yang humanis tidak dibangun atas dasar larangan dan hukuman, melainkan atas kesepakatan bersama yang menggunakan kalimat positif. Ketika siswa terlibat dalam merumuskan aturan, mereka merasa memiliki tanggung jawab atas kepatuhan dan lebih mungkin menginternalisasi nilai-nilai yang terkandung dalam aturan tersebut. Kalimat positif berfokus pada perilaku yang diinginkan, bukan yang dilarang; misalnya, "Kita berbicara dengan sopan" daripada "Jangan berteriak". Pendekatan ini membangun identitas kelas yang konstruktif dan menghindari stigma negatif yang sering muncul dari bahasa larangan.</p>
        <p>Proses merancang tata tertib kolaboratif dimulai dengan diskusi terbuka: guru bertanya kepada siswa, "Bagaimana agar kelas kita nyaman, aman, dan menyenangkan untuk belajar?" Siswa mengusulkan ide, guru memandu agar usulan menjadi konkret dan dapat diukur, lalu bersama-sama menyusun 5–7 aturan inti. Setiap aturan ditulis dalam kalimat positif, mudah dipahami, dan dikaitkan dengan nilai yang lebih besar (misalnya: rasa hormat, tanggung jawab, kerja sama). Aturan dipajang di kelas dengan desain visual menarik, dan guru secara konsisten mengingatkan dengan nada mendukung, bukan menghakimi.</p>
        <p>Contoh kalimat aturan positif: "Kita saling mendengarkan saat orang lain berbicara." "Kita menggunakan kata-kata yang sopan dan menghargai perasaan teman." "Kita menyiapkan alat belajar sebelum kelas dimulai." "Kita membantu teman yang membutuhkan tanpa diminta." "Kita menjaga kebersihan kelas bersama-sama." Dengan tata tertib yang kolaboratif dan menggunakan bahasa positif, kelas menjadi ruang yang aman, inklusif, dan penuh semangat belajar.</p>
    </div>
</div>