<!-- 7-2: Teknik Menulis Email atau Surat Undangan Panggilan Wali Murid dengan Nada Empatik -->
<div class="mb-20">
    <img src="https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&q=80&w=1200" alt="Email orang tua" class="w-full h-[400px] md:h-[500px] object-cover rounded-3xl shadow-xl mb-8">
    <h2 class="text-3xl md:text-4xl font-extrabold text-slate-800 mb-6"><i class="fas fa-envelope-open-text mr-3 text-emerald-500"></i>7-2. Teknik Menulis Email atau Surat Undangan Panggilan Wali Murid dengan Nada Empatik</h2>
    <div class="prose prose-lg prose-slate max-w-none text-slate-600 leading-relaxed">
        <p>Mengundang wali murid untuk pertemuan sering kali menimbulkan kecemasan baik bagi guru maupun orang tua. Email atau surat undangan yang ditulis dengan nada empatik dapat mengurangi ketegangan tersebut dan menciptakan suasana kolaboratif. Tujuan utama adalah membuat orang tua merasa dihargai, bukan dipanggil karena "masalah". Email yang empatik menegaskan bahwa guru dan orang tua adalah mitra yang bekerja sama demi perkembangan terbaik siswa. Ketika orang tua merasa diterima dan didukung, mereka cenderung lebih terbuka, kooperatif, dan konstruktif dalam pertemuan.</p>
        <p>Struktur email yang efektif dimulai dengan salam hangat, diikuti oleh pernyataan positif tentang siswa, kemudian penjelasan tujuan pertemuan secara jelas namun tidak mengancam. Gunakan kalimat yang menekankan kerja sama, seperti "Saya ingin berbagi pengamatan dan mendengarkan perspektif Bapak/Ibu" bukan "Saya ingin membahas masalah Ananda". Hindari bahasa yang terdengar menghakimi atau menyalahkan. Sertakan pilihan waktu yang fleksibel dan tawarkan opsi pertemuan daring jika diperlukan. Tutup dengan ungkapan terima kasih atas dukungan orang tua dan penegasan bahwa tujuan bersama adalah kebahagiaan dan kemajuan siswa.</p>
        <p>Contoh kalimat yang bisa langsung digunakan: "Bapak/Ibu yang terhormat, saya ingin mengundang Bapak/Ibu untuk bertemu guna berbagi pengamatan positif tentang perkembangan [Nama Siswa] dan mendiskusikan langkah selanjutnya bersama." "Pertemuan ini bertujuan untuk memperkuat kolaborasi antara sekolah dan rumah demi mendukung potensi terbaik [Nama Siswa]." "Saya sangat menghargai dukungan Bapak/Ibu selama ini dan berharap kita dapat terus bekerja sama dengan penuh pengertian." "Jika waktu yang saya usulkan tidak cocok, saya dengan senang hati menyesuaikan dengan jadwal Bapak/Ibu." Dengan nada empatik, undangan ini menjadi jembatan komunikasi yang sehat dan konstruktif.</p>
    </div>
</div>