<!-- 7-3: Simulasi Resolusi Konflik: Meminta Saran Strategi AI Menghadapi Siswa Tantrum/Bermasalah -->
<div class="mb-20">
    <img src="https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=1200" alt="Resolusi konflik" class="w-full h-[400px] md:h-[500px] object-cover rounded-3xl shadow-xl mb-8">
    <h2 class="text-3xl md:text-4xl font-extrabold text-slate-800 mb-6"><i class="fas fa-handshake mr-3 text-red-500"></i>7-3. Simulasi Resolusi Konflik: Meminta Saran Strategi AI Menghadapi Siswa Tantrum/Bermasalah</h2>
    <div class="prose prose-lg prose-slate max-w-none text-slate-600 leading-relaxed">
        <p>Menghadapi siswa yang tantrum atau menunjukkan perilaku bermasalah memerlukan ketenangan, empati, dan strategi yang tepat. Guru humanis tidak merespon dengan hukuman segera, melainkan berusaha memahami akar emosi atau kebutuhan siswa yang belum terpenuhi. Ketika guru mendekati siswa dengan rasa ingin tahu dan kepedulian, siswa merasa dilihat dan didengar, yang sering kali mengurangi intensitas tantrum. AI dapat menjadi mitra diskusi bagi guru untuk menganalisis situasi, mengidentifikasi pola perilaku, dan merumuskan strategi intervensi yang sesuai dengan konteks kelas dan kepribadian siswa.</p>
        <p>Dalam simulasi resolusi konflik, guru dapat menggambarkan situasi secara detail ke AI: usia siswa, pemicu perilaku, respons sebelumnya, dan dinamika kelas. AI kemudian memberikan saran bertahap: (1) teknik de-eskalasi saat tantrum terjadi, seperti memberikan ruang aman, suara tenang, dan pilihan terbatas; (2) strategi pasca-konflik untuk membangun kembali hubungan, seperti percakapan privat dan refleksi bersama; (3) rencana pencegahan jangka panjang, seperti mengajarkan regulasi emosi dan menyesuaikan tuntutan tugas. Guru dapat memilih dan menyesuaikan strategi yang paling sesuai, lalu mengujinya secara bertahap sambil mencatat respons siswa.</p>
        <p>Contoh strategi yang sering direkomendasikan: "Berikan ruang tenang: 'Saya lihat kamu sedang kesal. Mau duduk di sudut tenang sebentar? Kita bicara saat kamu sudah siap.'" "Validasi emosi: 'Wajar kalau kamu marah. Aku di sini untuk mendengarkan.'" "Berikan pilihan: 'Apakah kamu ingin mengerjakan tugas ini sekarang atau setelah istirahat 5 menit?'" "Gunakan kalimat 'kita' untuk menunjukkan kerja sama: 'Mari kita cari cara agar kamu bisa merasa lebih baik dan tetap bisa mengikuti kegiatan.'" Dengan bantuan AI sebagai mitra reflektif, guru dapat merespon konflik secara lebih tenang, konsisten, dan humanis.</p>
    </div>
</div>
