<!-- 7-6: Membuat Skenario dan Kalender Cek Kesehatan Mental (Mental Health Check-in) Mingguan -->
<div class="mb-20">
    <img src="https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?auto=format&fit=crop&q=80&w=1200" alt="Kesehatan mental" class="w-full h-[400px] md:h-[500px] object-cover rounded-3xl shadow-xl mb-8">
    <h2 class="text-3xl md:text-4xl font-extrabold text-slate-800 mb-6"><i class="fas fa-heartbeat mr-3 text-pink-500"></i>7-6. Membuat Skenario dan Kalender Cek Kesehatan Mental (Mental Health Check-in) Mingguan</h2>
    <div class="prose prose-lg prose-slate max-w-none text-slate-600 leading-relaxed">
        <p>Kesehatan mental siswa adalah fondasi penting untuk pembelajaran yang bermakna. Cek kesehatan mental mingguan yang terstruktur membantu guru mendeteksi dini tanda-tanda stres, kecemasan, atau kesulitan emosional sebelum berkembang menjadi masalah serius. Skenario check-in yang baik bersifat sukarela, rahasia, dan tidak menghakimi; siswa merasa aman untuk jujur tanpa takut dihukum atau dicap. Kalender check-in yang konsisten menunjukkan bahwa guru peduli pada kesejahteraan siswa secara menyeluruh, bukan hanya pada pencapaian akademik.</p>
        <p>Untuk membuat skenario check-in, guru dapat menggunakan alat sederhana seperti formulir anonim, kartu emosi, atau sesi circle time singkat. Pertanyaan kunci bisa berupa: "Bagaimana perasaanmu minggu ini?" "Apa yang membuatmu senang atau stres?" "Apa yang kamu butuhkan dari guru atau teman?" Hasil check-in didokumentasikan secara rahasia oleh guru, lalu digunakan untuk menyesuaikan pendekatan pembelajaran, memberikan dukungan individu, atau merujuk ke konselor jika diperlukan. Kalender check-in bisa dijadwalkan setiap hari Jumat pagi atau Senin siang, disesuaikan dengan ritme kelas.</p>
        <p>Contoh pertanyaan check-in: "Skala 1–10, seberapa baik perasaanmu minggu ini?" "Apa satu hal yang membuatmu bangga minggu ini?" "Apa satu hal yang sulit bagimu minggu ini?" "Apa yang akan membuatmu merasa lebih baik minggu depan?" "Apakah ada yang ingin kamu bicarakan secara pribadi dengan guru?" Dengan sistem check-in mingguan yang konsisten dan empatik, guru menciptakan budaya kelas yang peduli, aman secara emosional, dan mendukung kesehatan mental siswa.</p>
    </div>
</div>
